### ISSUE TITLE
[epic] State of Sensemaking 2021 v1 alpha website

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#1]
We are creating a report on the "State of Sensemaking" that inventories and maps the emerging ecosystem of sensemaking and culturemaking that Life Itself and others are participating in and contributing to.

See more at: https://lifeitself.us/ecosystem-mapping/

## Acceptance

* [x] Database with X organizations and Y people
* [ ] Website with this information on it
  * [ ] Map life-itself/ecosystem#24 
  * [x] Search and browse
  * [x] Profile page for each org or person
* [x] Announce / PR and Publicity 

## Tasks

Brief

* [x] Job stories for 2021 v1
* [x] Any examples of existing sites for inspiration

Content

* [x] Database of orgs
* [x] Database of people

Website

* [x] Website mockup
* [x] Profile page per org / person
* [x] Website front page

### 6 Oct MVP

Site itself

* [x] Profile page working with basic info we already have (e.g. logo)
* [ ] (?) we are using next/image to optimize images ...

Minor

* [ ] Set titles again

Content work

* [x] Brief charlotte about including a better picture of even a screenshot (?)
* [ ] Do rest of items
* [ ] Add twitter and social media

Extras

* [ ] Screenshots of websites
* [ ] Automate extracting information with a command line tool (~2h)
