### ISSUE TITLE
Website Design v1

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#10]
We want to get a rough design for the site in e.g. Figma

Mockup in figma in progress: https://www.figma.com/file/u3KjFsTPbQfosVjuG5awhF/State-of-Sensemaking-Mockup?node-id=0%3A1

## Acceptance

* [ ] Mockup theme (front page hero)
* [ ] Mockup front page
* [ ] Mockup profile page

## Tasks

* [ ] Mockup theme (front page hero)
* [ ] Mockup front page
* [ ] Mockup profile page
