### ISSUE TITLE
Design Research on existing ecosystem mapping / directory style sites

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#11]
Research / mockups on sites (not just design but UX / map)

When designing the site (and generally doing UX, or creating viz) I want to have inspirational examples so that I can use these to guide what we do

## Acceptance

* [ ] Notes / Moodboard showing result of research **DONE> See https://www.figma.com/file/rIm4V6eauW1SPGlVGA0F4H/LifeItself-Ecosystem-Design-Research?node-id=0%3A1**

## Tasks

* [x] Identify examples of "directory" sites
* [x] Screenshots etc + notes

### Examples

* [ ] https://knightfoundation.org/features/civictech/
  * [ ] https://knightfoundation.org/wp-content/uploads/2019/06/knight-civic-tech.pdf
* [ ] https://www.cohabitat.io/en/projects/
* [ ] https://www.awwwards.com/awwwards/collections/free-fonts/
