### ISSUE TITLE
Core Content for the Site

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#13]
We need some key content e.g. a short blurb on home page. A fuller about page with background. Maybe a page on "naming" the space?

## Acceptance

Most blurb content is now here https://docs.google.com/document/d/1zyxadZtRpHYMZ35Rxrq_jgNxMxkYg7K3guhqf7XeR48/edit#

* [x] Blurb for front page
  * [x] Tagline
  * [x] Paragraph (why, what, how ...)
* [x] How to add your organization (how to edit your info)
* [x] About page **Very solid now: https://ecosystem.lifeitself.us/about/**
  * [x] Why
  * [x] What
  * [x] How
  * [x] Disclaimer 
* [ ] ~~2021 report ...~~

## Tasks

* [ ] ...
