### ISSUE TITLE
Contributor guide update (Nov 2023)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#144]
Update the contributor guide so that it is up to date.

## Acceptance 

- [x] Archived version of v2021 contributor guide (which contains instructions for editing via Obsidian and via GitHub)
- [ ] Review and revise the existing contributor guide 
- [x] #170
- [ ] Updated process for third-party suggestions/submissions

## Tasks

- [ ] instructions on how to contribute
- [ ] instructions for consistent formatting e.g. of frontmatter (esp where necessary for build to work)

### Creating new contributor guide

- [x] Consolidate the guide into one page by consolidating the 'contribute' and 'contributors guide' page  **✅2023-11-30**
- [ ] Figure out how we want the contributors guide to look
  - [x] Do we want this for novices or experts/editors/curators? **✅2023-12-12 only do the expert/editor contributor path only for now (via obsidian)**
- [x] Integrate (and update) relevant material from https://github.com/life-itself/labs/issues/172 @matthewmccarthy11 
- [x] Integrate (or link to (?)) Obsidian configuration instructions https://github.com/orgs/life-itself/discussions/927 @matthewmccarthy11 
- [ ] Put a link to the discussion forum where people can view potential orgs that might be added and add their own

**Comment by matthewmccarthy11** [comment]
The following are all organizations which have been provided and are not included in cohere+ Pluriversa, Democracy Policy Network, Regenerators, Pacific Integral, Oika, Complexity Weekend, MetaCurrency Project, Cultural Strategies Council, A Fairer Society, Sayara International, Intentional Society, The Context Institute, TEEM Lab, Ashes of the Magi, The Nongrowth Society, Black Forest School of Metamodernism, Coexistence Awarnessbased Intrinsically

**Comment by matthewmccarthy11** [comment]
**The following are all organizations which have been provided and are not included in the Life Itself Ecosystem:** Pluriversa, Democracy Policy Network, Regenerators, Oika, Complexity Weekend, MetaCurrency Project, A Fairer Society, Sayara International, TEEM Lab.

**Comment by rufuspollock** [comment]
@catherinet1 yes i would say that getting the metadata sorted is a blocker for the finished version of this.

**Comment by rufuspollock** [comment]
@matthewmccarthy11 /cc @catherinet1 split out the processing old submissions to separate issue #170

**Comment by catherinet1** [comment]
@matthewmccarthy11 @elisapaka i just added as a task above to integrate (and update) relevant material from https://github.com/life-itself/labs/issues/172

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. Did some work. Plus this is now replaced IMO by https://forum.secondrenaissance.net/t/how-to-contribute-to-the-organization-directory-database/31
