### ISSUE TITLE
[epic] Search and Filtering

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#15]
When browsing the directory I want to filter and facet so that I get an overview and find organizations I want

When arriving on the site I want to quickly search for the organization I want so I can jump to that page

## Acceptance

* [x] Simple search box on main page with profiles
* [x] Faceting (display, counts, filter by)

## Tasks

* [x] Select approach to doing this **Trying in app with fuse.js e.g. can follow https://cheatcode.co/tutorials/how-to-implement-client-side-search-with-fuse-js**
* [x] Simple search box with reactive results
* [x] Facets
  * [x] Show facets
  * [x] Show facet counts
  * [x] Make facets look nice (too many and a bit larger atm) - or is this a content thing (have fewer topics)
* [x] Filtering by facets

## Analysis

Options

* Algolia - https://www.algolia.com
  * Structured: free for what we want probably. Some more effort to set up
  * DocSearch: https://docsearch.algolia.com not really the exact match but free, hacky and fast and may work because we have a separate page for each organization. however, can't power filtered search on the front page ...
* Typesense: Open Source and good but if we want hosted (and we do) then there is a substantial cost => ❌
* DIY: not a big problem given size of DB. Issue is finding React widgets or similar OOTB that we can use for doing filtering etc. Otherwise we have to implement ourselves which is a PITA.

### DIY

Here's a list of libraries https://bestofjs.org/projects?tags=search

* fuse.js https://github.com/krisk/Fuse will go for this for now as seems the best and most used
* flexsearch: good but all about performance (we don't care given how much info we have) plus a bit complex (less good docs)
* list.js - won't use as we have got structured data so might as well reuse

![image](https://user-images.githubusercontent.com/180658/136814340-b9adda29-3180-49b8-b5e7-c4c1914102d0.png)
