### ISSUE TITLE
Update frontmatter for new and old profiles 

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#150]
This issue is to implement the latest agreement re what metadata fields we're adding to profiles for the time being: #143 

## Acceptance

- [x] Cohere template is up to date, including guidance on field definitions. **Template is here, with link to documentation: template is here: https://github.com/life-itself/second-renaissance/blob/main/content/templates/profile.md.  **
- [x] All new orgs in tbd folder are up to date with the latest template **All profiles in Cohere+ DB/directory are complete with correct frontmatter. See https://github.com/life-itself/second-renaissance/tree/main/content/ecosystem/cohere/profiles.**
- [ ] All 2021 orgs in profile folder are updated ❌ **Did not update 2021 profiles to use same frontmatter**
- [x] Code is updated to build with new metadata **#318 is complete**

## Tasks

- [x] Update the cohere template including docs for field definitions https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=1239522110 **Template is up to date, but currently includes template and documentation/guidance in the same file. Next is to create clean version of template with separate documentation**
  - [x] Create supporting documentation **Cut guidance out of template and pasted it in new file: https://github.com/life-itself/ecosystem/blob/main/content/templates/profile-documentation.md**
  - [x] Create clean version of template **Updated template file to contain only headings here: https://github.com/life-itself/ecosystem/blob/main/content/templates/profile.md**
    - [x] remove About heading? **Haven't done this as helps to have an 'About' section to refer to in the documentation**
- [x] Update existing new orgs (in tbd folder)
- [ ] Update 2021 orgs in profile folder ❌ **Did not update 2021 profiles to use same frontmatter**
  - [ ] Update code for that ... (as our current profiles page depends on current metadata structure)
- [x] Merge tbd into profiles (or even merge everything into the root directory?) **All Cohere+ profiles are in this folder: https://github.com/life-itself/second-renaissance/tree/main/content/ecosystem/cohere/profiles.**
- [x] Add agreements from notes below into template documentation: https://github.com/life-itself/ecosystem/blob/main/content/templates/profile-documentation.md **2024-10-25 updated template documentation.**

### Catherine qs re data collection and input as of 2023-11-30

- [x] What is our agreement re standard format for filenames? Capital letters? Spaces? **There must not be spaces in filename.**
- [ ] When do we start putting things in profile folder? (instead of tbd) **2024-10-25 Not relevant**
- [x] (Rufus) do we want a clean template and separate documentation guide for filling it in (e.g. template/documentation) **✅2023-11-30 yes i'd just have a file like `Profiles Documentation` or whatever you like for now - or even just put in the contributors documentation**
  - [x] Maybe put link to documentation in the template (so that people don't just fill in the template without referring to the documentation ) **Did this**
- [x] todo still: agree on not-found convention **Leave blank as code is such that if frontmatter field is blank it won't be displayed on profile page**
  - [ ] propose: use not-found and not-applicable. e.g. If i don't fill in a location for an org because it is an international network then I want to use something which indicates that this category doesn't apply to this entry. (leaving it empty is ambiguous, and recording it as not-found suggests that I'm missing information as to why it is not-found) ❌ 
  - [ ] clarify that frontmatter fields should only contain data in the precise format specified in documentation?, e.g. for locations that is [city], country. Otherwise it is too tempting to put in data in other formats when things don't quite fit .. **didn't add a specific note to this effect, I think that is the general point of the documentation guidelines**

### Agreements

- Put images directly in assets folder
- use obsidian links as easiest, least error prone approach ie. start typing ...[[...]]

**Comment by catherinet1** [comment]
cc @matthewmccarthy11

**Comment by rufuspollock** [comment]
@catherinet1 is this still relevant? If so can we update with current status and next steps. If not, let's close with message about why etc.

**Comment by catherinet1** [comment]
FIXED. 
- Cohere+ directory/database is complete: https://github.com/life-itself/second-renaissance/tree/main/content/ecosystem/cohere/profiles. 
- Frontmatter template is here: https://github.com/life-itself/second-renaissance/blob/main/content/templates/profile.md.  
- Template documentation (guidance on filling out template) is here: https://github.com/life-itself/ecosystem/blob/main/content/templates/profile-documentation.md

WONTFIX. 
- Did not update 2021 profiles to use the same frontmatter as Cohere+ profiles.
