### ISSUE TITLE
Document and refine workflow for adding orgs to directory as of Nov 2023

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#152]
Adding orgs to the directory is a major part of the work and we want a clear process for doing this ...

## Acceptance

- [x] Diagram of current workflow and status **✅2023-11-29 https://link.excalidraw.com/readonly/RnwkDDa28bsX8JwfaGHv and copied main image below**
- [ ] Identify changes if any
- [ ] Implement

## Tasks

- [x] Draw a diagram in excalidraw of the workflow process (e.g. longlist, evaluation, write-up, review, publication etc) and annotate with e.g.
   - rough status at each stage of pipeline e.g. how many we have there
   - where we do that stage of the pipeline
   - improvements ...
- [x] Review **✅2023-11-30 rufus and catherine**

### Current workflow

![Image](https://github.com/life-itself/second-renaissance/assets/180658/394c2288-0c3f-4e00-b351-a43be4c9b71a)

### Cohere+ research profile priorities

Question: What are our priorities for the Cohere+ ecosystem research profiles?

#### Primary priority 
- About :fire: **We want some kind of description**
  - Start to use Obsidian backlinks for key concepts 
- Key Educational Resources :fire: **if appropriate, bc overall project has educational purpose/focus and WP4 would draw on educational resources we find**
- Connections :fire: **so that we can see some clusters emerge from connections across the space, so that we can get a sense of the field through relationships in the space**
  - include inspirations/connections to key figures/concepts too
- All frontmatter except sector and activity :fire: **helpful to have some strucutred data for comparison across key fields, esp fields that are pretty straightforward to fill in**

#### Secondary priority
**These things seem helpful, but also take more time and we're not clear on final sector and activity categories yet cf #168**
- Sector
- Activity
- Theory of Change

#### Tertiary priority
- Key People

**Comment by catherinet1** [comment]
i added analysis of what are our current research priorities for the cohere+ profiles in the DB in notes section above. So that we have agreement on what to focus on first in our org research when we have limited time. i.e. i propose we would focus on filling out the primary priority fields first. @matthewmccarthy11 and i discussed briefly yesterday. @rufuspollock would you take a quick look and give thumbs up or flag concerns?

**Comment by rufuspollock** [comment]
@catherinet1 i think we are abusing this issue a bit 😉 the metadata discussion was supposed to be in https://github.com/life-itself/ecosystem/issues/143 - plus we now have https://github.com/orgs/life-itself/discussions/950

I think we want to focus this just on the workflow (and close asap) and re-open #143 if we need to. 

wdyt?

**Comment by rufuspollock** [comment]
FIXED to an extend and now INVALID as OBSOLETE. I don't think is really that relevant anymore.
