### ISSUE TITLE
Switch to Digital Asset Management Solution (Cloudinary) for Images

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#16]
When displaying our website we want all images to reliably load so that the site looks professional and good

* Currently when we use links to images (e.g. for org logos) these are to the link on the org site or elsewhere. These can break (e.g. links to FB images often "expire"). This then breaks on our site. Caching versions ensured we always have a copy.
* Secondarily, have an instance in a DAM like cloudinary allows us to do resizing and stuff like that efficiently

When presenting an org's profile page we can include a screenshot of their website (super useful IME) so that people have a sense of what they are like

## Acceptance

* [x] All logos / primary images for orgs are in cloudinary in the ecosystem folder https://cloudinary.com/console/c-5b6743fc069522598c97d1e3f699e6/media_library/folders/be1b12676189777871bd22224e31c67653
* [x] ~~We  are able to use the DAM either to cache homepage screenshots or to transparently prep them (cloudinary seems to support the latter - question is what happens if their site goes away ...)~~ **WONTFIX as more complex than this. See #22 for dedicated issue**

## Tasks

* [x] We have selected a provider **DONE. Cloudinary as it was only one providing DAM afaict**
* [x] We have moved all images over

### Image hosting providers / Digital Asset Management

* See analysis here: https://www.notion.so/11b5deedc98e4cada724ac7f9c505984?v=37e371d0ac43420894fa607ee47f3f0d
  * Note: only cloudinary seemed to do DAM as as well. Others were more image transformation. Plus cloudinary had url2png integration for screenshosts - https://cloudinary.com/documentation/url2png_website_screenshots_addon
