### ISSUE TITLE
Decide on key categories for sector/topic and activity frontmatter fields for Cohere+ database

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#168]
e.g. How does old "topics" relate to current "sectors"?

## Tasks

- [ ] What is the situation and complication here right now? **Have a bunch of old profiles using one taxonomy and have a bunch of new profiles using a different one. Also not sure that the current taxonomy is super clear, e.g. what is the difference between Convening and coordination and Networks and Forums activities?**
- [ ] Get lists of all topics/sector and activity categories used
  - [ ] old ecosystem profiles
  - [ ] cohere+ spreadsheet 
 - [ ] analyse: review and note 
 - [ ] decide on merged version ?

**Comment by catherinet1** [comment]
cc @matthewmccarthy11 i created this issue related to frontmatter categories and  how does 'topics' field relate to 'sector' ?

**Comment by rufuspollock** [comment]
@catherinet1 is this still relevant?

**Comment by catherinet1** [comment]
FIXED/WONTFIX. We have a list of sector and activity categories which we are using for the Cohere+ database. We did not integrate/merge these with the categories used in the 2021 profiles. Can consider integration/merging of databases in the future.
