### ISSUE TITLE
Finalize topic list and apply to orgs

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#18]
## Acceptance

* [x] Topic list is finalized
* [x] All items live in current directory have topic well applied

## Tasks

* [x] Refine list
* [x] Systematically apply (review application) @theo-cox 
* [x] Selected emojis
* [ ] ~~Selected image from unsplash for each topic~~
* [x] (Rufus comment) - i wonder if we could reduce list a bit to e.g. 7 or so. A bit lengthy atm.
* [ ] Also maybe one word titles (?)
