### ISSUE TITLE
Organization Profile Page v1

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#19]
We have a working page atm but we need to finalize. Somewhat dependent on #17 and #18 

## Acceptance

* [x] Profile page working with info we already have (e.g. logo) **~~Most done. Remaining is people~~. ALL DONE**

BONUS

* [ ]  Show home page screenshot as well as logo (if we have it)

## Tasks

* [x] Markdown format description
* [x] Show location (extract primary location) **Done crudely**
* [x] Show activities (and link to page for these)
* [x] Show topics
* [x] Show people using user-icon from heroicons

## Analysis

Ideas for stuff we could add e.g.

* a word cloud based on text on the orgs' front page see e.g. https://github.com/jasondavies/d3-cloud
