### ISSUE TITLE
Website technical architecture

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#2]
There are various technical architecture considerations to resolve.

## Tasks

* [x] do we integrate with wordpress **NO**
* [x] how do we store and manage content/data e.g. spreadsheet on own, markdown on own, a mix ... **ATM just the spreadsheet**
  * [ ] how do we manage relationships from org to org and org to person **We don't atm**
* [ ] How do we acquire and store images? **We use cloudinary. See #16**

### Content/Data Architecture

3 options

* In spreadsheet
* In markdown files
* Mixed

For now go for option 1.

### Research on image

* [ ] image hosting services https://www.notion.so/11b5deedc98e4cada724ac7f9c505984?v=37e371d0ac43420894fa607ee47f3f0d
* [ ] site screenshot services.
  * [ ] https://urlbox.io

### Aside: Wordpress + Next.JS

* Official next.js approach (basic and solid) https://github.com/vercel/next.js/blob/canary/examples/cms-wordpress/README.md
* 227 ⭐ more sophisticated https://github.com/imranhsayed/nextjs-headless-wordpress
* 323 ⭐ pretty complex full featured https://github.com/WebDevStudios/nextjs-wordpress-starter
