### ISSUE TITLE
Editable Content Pages (in markdown)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#20]
When adding content to the site e.g. in #13 I want to have a way to add and edit pages (in markdown) and have them show up on the site so that they are visible to visitors

## Acceptance

* [x] I can add pages in markdown or MDX and they automatically show up in the site url space e.g. if i add `/content/about.md` that shows up on the site at `/about/`

## Tasks

* [x] Add catch all url map for these
* [ ] Add brief documentation about how this works (?)
