### ISSUE TITLE
Process 2023-12-20 Meeting notes scratchpad

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#207]
# 2023-12-20

- [x] Meditation
- [x] Check-in
- [x] Agenda
- [ ] Updates follow up on previous next actions
  - [ ] Exemplars: https://github.com/life-itself/ecosystem/issues/186 
  - [ ] Contributors guide ...see issue https://github.com/life-itself/ecosystem/issues/144. Obsidian contributors guide has been put in google docs here: https://docs.google.com/document/d/1Kgf4zQ58c6iJFRU5KXz24KFcjAlgFvmHVn-SJkfpcis/edit?usp=sharing Elisa has reviewed, Catherine needs to review, and screen shots still need to be added. + See qs below 
- [ ] Plan of work
  - [ ] Project status
  - [ ] Next steps
- [ ] Get clear on next actions for now until the end of the year
  - [ ] Gap Analysis @catherine
    - [ ] interviews complete. Did >10
    - [ ] Send out a survey in the new year?

## Updates re past actions
- [ ] Create an archived version of the contributors guide. **Archived version can be found here**: https://github.com/life-itself/ecosystem/blob/main/content/contribute%20guide1.md **As soon as the obsidian guide is complete and reviewed, the new will guide will be put in replacement of the existing contributors guide.**
-  Process existing backlog submissions: **issue has been closed https://github.com/life-itself/ecosystem/issues/170**

## Questions/comments re exemplars

- In 42 acres examples there are a lot of backlinks- we are making stubs for all of them? **Yes I think I made stub pages for all that were new. Some already existed as notes.**
- Just flagging that the 'picture' on CSA is in a slightly different spot than 42 acres **I think it's okay as is. We could try to come up with standard guidelines for formatting but I think in a wiki hard to ensure that everyone will stick to these all the time**
- The format for each one is individualized- I assume that's how we want to do it for now? **Yes--see Principles of Mapping section, wiki over database**
- Joysong collective seem US-based? What presence do they have in Europe? **I included them because they described themselves as a "global" community but not sure of specific presence in Europe**

### Rufus
- Add short description (maybe in frontmatter)
- Move overall discussion/reflection to another thread?
- Retreat centres ?
- Does "integrated" do enough work for us?
    - Many people in postmodern and metamodern tick this box
    - **What is the subtle kind of "integrated" approach that is closest to the centre?**
- Post modern and metamodern both want paradigmatic change. How do we distinguish between the two?
- Regeneration (green) vs evolution (teal)
- McGilchrist - integration of intuition and reason
- Wellbeing 
- Inner development as political/ontological politics/politics of being as a signifier of "metamodernism"
- What are the aspirations of post modernism? (Wellbeing? Definitions are anathema) What are the aspirations of metamodernism? (Evolution?)
- Modernity mostly neglects the inner
- Postmodernity remembers some of the inner and often connects this to outer change in some way. And connecting with nature rather than dominating.
- Later we might want to distinguish between postmodern and metamodern
    - e.g. out of word clustering
- Postmodern - you have to respect differences of opinion/perspective. Metamodern can re-integrate multiple worldviews/multiple truths. Resolved into a meta-systemic holding or context. E.g. in an evolutionary path. 
- Postmodern is current dominant edge flavour of our society
- distinction between framing/worldview/theory of change/vision and what they're actually doing, 
  - e.g. 42 Acres former is upper left and action is more lower
  - CSA action is more lower left and worldview is more lower right

### Catherine 

- Spirituality?
    - Rufus: spirituality comes back in postmodernism. Intuitively, metamodern/teal has religion rather than spirituality. Spirituality in postmodernism tends to be quite individualised. Return to an agreement on a cultural spiritual frame. cf Church of Interbeing (on a scale that coheres a society)? 
- Rename Theory of Change something like Principles of Change? 

## Questions re contributors guide

- [x] Do we want to include configuration settings as well? Or just point to the github discussion? **This stuff will go in Markdown guide**
- [ ] We only have a spot for 'additions' and 'organizations'. Should we include 'editing' and 'topics'?
 
### Catherine
- [x] Close initial set of exemplars https://github.com/life-itself/ecosystem/issues/186
- [x] 5-6 more profiles (create new issue). **Issue created: https://github.com/life-itself/ecosystem/issues/204**
- [ ] Process today's meeting notes
- [ ] Review and tidy/update Labs issues @catherine
  - [ ] Gap Analysis @catherine 

### Matthew
- [ ] 2 new profiles by tomorrow sync w Rufus
- [ ] contributor guide
- [ ] clearing up ecosystem backlog of issues

**Comment by rufuspollock** [comment]
FIXED. This happened to the extent it happened.
