### ISSUE TITLE
Primary image for organizations: curated, logo, or screenshot of their website ...

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#21]
When viewing a profile of an organization I want to see an image to get a quick sense of what they are like and about

When viewing an overview of an organization i want to see a thumbnail to get an intuitive sense of them (TODO: do we want this rather than their logo?)

## Acceptance

* [ ] We have decided what is primary image for an organization (is it custom, home page, logo) **If we have custom use that. Otherwise use home page. Otherwise use logo. Would also be nice to have a "square" one e.g. favicon or twitter for use in visualization**
* [ ] We have a plan for getting these ... **we have plan for home page and logo. Custom one is up to people**

## Tasks

* [x] List options
* [x] Pro/cons (e.g. look and cost)
* [x] Recommendation

## Analysis

As an example for Ekskaret, here's our original image:

![](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQWoib85SKGtGKhyJAzyKAYM3wf6iIkM4Ic09-BLF8wbyp9gUHC)

vs the logo:

![](https://res.cloudinary.com/ds7qslkd0/image/upload/v1633425250/Ecosystem%20Mapping/Eksk_C3_A4ret-logo_5900x2344_gr_C3_A5_transpbg_28tight_29_oxiwsi.png)
