### ISSUE TITLE
Process for taking screenshots of websites 

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#22]
When providing info on an organization/initiative I want to have a screenshot of their website so that I have a good sense of them (both feel and what they do) (cf #21)

## Acceptance

* [x] What service do we use? **[Microlink.io](https://microlink.io/docs/api/parameters/screenshot) with backup of https://apiflash.com**
* [x] Where do we cache images (if anywhere)
* [x] How do we serve them ... (if different)

## Tasks

* [x] What service do we use **Use microlink.io**
  * [x] List of options for screenshot services: urlbox, url2png, apiflash
  * [x] Evaluate them
  * [ ] Choose one
* [x] Do we cache? **ANS: yes, i think since we then have a permanent copy plus we need this for resizing etc (though could be a way to sort of proxy but inelegant**
* [x] How do we serve? **ANS: straight out of our image storage system**

## Analysis

- urlbox.io $29/month seems pretty good  ... however not integrated with cloudinary and more expensive
- url2png: $29/month. original but somewhat dated. Integrated with cloudinary (but not sure how useful that is if we want to cache)
- apiflash: 0/100mo or $7/1000.  good so far ... Quality is good. Good API. Pricing is a lot better than other two 
- thumbnail.ws (free for small amounts
- https://microlink.io - 12euro / 14k requests. (0 or 100 / day). By far the best and clearly good dev behind it

Notes

* Testing with lifeitself.us
  * url2png: very poor with big white space
  * urlbox.io better but still had some space, plus no way to really play around (e.g. full page) without signing up
  * apiflash: the best and easy to play around with - see e.g. https://api.apiflash.com/v1/urltoimage?access_key=0633900f9b8d453191b8deef9dd3e910&url=https://lifeitself.us&full_page=true&height=768&width=1366&quality=100
