### ISSUE TITLE
Complete 'basic' profiles for 80 organisations

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#226]
Follow-on from #217 

## Acceptance

- [x] 80 organisations in total have 'basic' profiles complete (see research status in notes below), and status is updated in Index tab of https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=568491195 **2024-06-07 ~60 profiles complete in repo and now have ~80 more in new [spreadsheet](https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit#gid=0)**

## Tasks

- [x] Desk research to fill in frontmatter, description, and image for 80 organisations in the ecosystem repo
  - [x] Plus also fill in rough rating of closeness to centre with v quick + dirty notes
- [ ] Migrate relevant data from 'Data collection' tab in https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=0 into repo profiles

### Research status

1 (basic) means:
- frontmatter fields complete (where data found)
- description pasted in
- image (normally screenshot of homepage) both in frontmatter and pasted in

2 (complete) means:
- relevant content under all template headings
- in good, shareable format

**Comment by catherinet1** [comment]
2024-02-12 update: Completed 2 basic profiles.

**Comment by catherinet1** [comment]
2024-02-13 update: Completed 3 basic profiles.

**Comment by catherinet1** [comment]
2024-02-14 update:
- Redid 2 profiles from yesterday as somehow managed to delete branch before merging:(
- 2 new profiles

**Comment by catherinet1** [comment]
2024-02-16 update:
- 5 new profiles

**Comment by catherinet1** [comment]
2024-02-19 update:
- 5 new profiles

**Comment by catherinet1** [comment]
2024-02-22 update:
- 5 new profiles

**Comment by catherinet1** [comment]
2024-02-24 update:
- 4 new profiles

**Comment by catherinet1** [comment]
FIXED. Have ~60 complete profiles in repo and now have ~80 in new [spreadsheet](https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit#gid=0).
