### ISSUE TITLE
Scrape info on orgs from their websites (automated)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#23]
We want to automate getting basic info from websites using their metadata (e.g. open graph, social etc).

Bonus

* Get the screenshot - would solve #22 
* Get the content

## Acceptance

* [x] Working script to extract key info **See `scripts/etl.js:getMicroLinkInfo`**

## Tasks

* [x] Identify library for doing this
  * [x] Find options **Fortunately had starting doing this a few years ago for another project**
  * [x] Review and select **Found a great one (that's new in fact): https://github.com/microlinkhq/metascraper and it has an associated service https://microlink.io/docs/api/parameters/meta that includes screenshots https://microlink.io/docs/api/parameters/screenshot**
* [x] Write script
* [x] Run it
