### ISSUE TITLE
Geographic Map of Organizations

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#24]
When viewing an entity i want to see where they are located on map esp if they have multiple locations

When viewing a grouping of entities i want to see clustering on a map to get a sense of density

## Tasks

* [ ] Geocode locations **Probably use https://api.opencagedata.com/geocode/v1/json?q=PLACENAME&key=YOUR-API-KEY**
* [ ] Display locations on a map
  * [ ] Identify library **React simple maps seems decent https://www.react-simple-maps.io/examples/custom-markers/**
  * [ ] Implement it

## Analysis

Simple maps ...

https://www.react-simple-maps.io/examples/basic-markers/

Geocoding

https://opencagedata.com/api#quickstart
