### ISSUE TITLE
Move 2021 report to its own page and tidy

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#249]
Intention: have one integrated landing page for PIP that is more report like.

## Acceptance

Overall goals: 

- [x] Move PIP work to own section e.g. `/ecosystem/pip` **https://secondrenaissance.net/ecosystem/pip**
  - [x] Update Hero section e.g. with new title + date
  - [x] Rearrange page? e.g. add Executive Summary report text at the top. Move circular viz to top
- [x] Upload PDF of full report with PIP framing and link on webpage **PDF here: https://drive.google.com/file/d/1y-DdWVe6ak-6yHVHFZkoEhLhTqty3QzY/view?usp=sharing and linked via Read full report button on PIP landing page**
  - [x] Sets out the case for "PIP for change"
  - [x] Integrates current landing page, about page, Viz, Any other relevant stuff

## Tasks

```[tasklist]
### Tasks ...
- [x] Relocate landing page to `ecosystem/pip` or similar **✅2024-04-02**
- [x] Move profiles and fix links from directory etc if needed **✅2024-04-02**
- [x] Update hero section (see "Hero section" below) **✅2024-04-18 See "Hero" section in [PIP Report redraft 2024](https://docs.google.com/document/d/1Q5GOjaBJB1WHPojZnvH3FApAYsKb6AYrnvOk2c6ABr0/edit)**
- [x] Consolidate, update, and add to existing material to form a report (see "Report" below)
- [x] Move from current `/ecosystem/pip-2021` to simple `ecosystem/pip` **✅2024-05-19**
- [x] 2024-06-04 N.B. PIP profiles are “broken” in the sense that they no longer show the frontmatter data… what happened? How do we fix this? E.g. https://secondrenaissance.net/ecosystem/pip/profiles/rebel-wisdom  **✅2024-06-06 FIXED had missed out changing something in code to set profiles layout after relocation of pip-2021 to pip**
- [x] Redirects for all the old stuff here ... e.g. `/viz/`, `/profiles/` etc ... e.g. lifeitself.org/ecosystem and ecosystem.lifeitself.org should go to ecosystem landing page instead of 2r landing page **✅2024-06-28 fr vis and profiles. Leaving ecosystem.lifeitself.org to redirect to secondrenaissance**
- [x] Delete secondrenaissance.net/viz (or move to ecosystem/pip)? **✅2024-06-28**
```

### Hero section

- [x] Replace the carousel title with "PIP for Social Change: Mapping an Emerging Ecosystem of Paradigmatic, Integrative, and Pragmatic Change Agents"
  - [x] Move the names that are currently in the carousel  (Metamodern, Polycrisis, Metacrisis, Great Transition, Liminal) --> e.g. Mention them in intro
- [x] Change PIE to PIP (see hero)
- [x] Change buttons to be clearer, e.g. Discover --> Read More; Explore --> Explore organisations
- [x] Published date in the hero section (with maybe updates info e.g. published Oct 2nd 2021 - updated Feb 2022)
- [x] Correct authors to just be Life Itself ...

### Report

**Draft here: [PIP Report redraft 2024](https://docs.google.com/document/d/1Q5GOjaBJB1WHPojZnvH3FApAYsKb6AYrnvOk2c6ABr0/edit)**

ToC sketch:
- [x] Title page: Title, Subtitle, Date (Oct 2021), Authors **In "Hero" section**
  - [x] ❓ Maybe abstract **In "Hero" section**
- [x] Executive Summary: This report presents the results of XXXX …
  - [x] Brief intro (maybe with short disclaimer woven in)
  - [x] 🆕 [quick] Top level info e.g. number of organizations included, what we found …
  - [x] 🆕 [summary of method section] work involved e.g. research interviews, collecting XXX organizations, selecting Y for further analysis …
  - [ ] Summary of results specifically the name "PIP" and what it means
    - [ ] 🆕❓ contrast of this approach to social change with existing approaches (concretely) (maybe a table)~~
  - [ ] ❓ explain that we whilst we compiled a list of individuals we did not include it in the report (why? Because less comfortable making a list of individuals b/c privacy, more controversial re who is in and out etc) **❌ CT: I would just leave this out**
  - [ ] 🆕❓ give examples or organizations ....
- [x] Introduction
  - [x] Background of this effort: emerging ecosystem (and our work on it)
  - [x] General plan of work / current focus: what, why, how (?)
  - [x] Why map (special emphasis)
  - [x] 2020 report **Included in "Background" section --> Previous work**
- [x] Method??
  - [x] Who we interviewed **Also included some highlights of language used to describe the space and people/orgs mentioned**
  - [x] How many orgs surveyed **See "Data collection: organization profiles" section**
  - [x] Trial of various difference methods for “making sense” e.g. different classifications, geo locations
  - [x] Classification of orgs
- [x] Results
  - [x] Brief intro
  - [x] Metacrisis/polycrisis context
  - [x] PIP: 3 key features of approach
  - [x] Other stuff: post-individualism, wholism, counter-culturalism
  - [x] Other stuff: language and buzzwords **Incorporated into brief intro at the beginning of results section**
  - [x] Concepts **🆕 Added this brief section, based on this "Conceptual Map" [sketch](https://docs.google.com/drawings/d/1PXz7tqwSvSzSJEumKJqJLqnf4qSQst0LH3g1hL2dKLw/edit)**
  - [x] Activities **Added table of activities, descriptions, and no. of orgs per activity**
  - [x] Topics **Added table of activities, descriptions, and no. of orgs per activity**
  - [x] Visualization/maps
  - [x] Directory
- [x] Appendices
  - [x] Appendix: Limitations
  - [x] Appendix: Partnerships **❌  Moved to ecosystem mapping landing page instead**

## Extras

```[tasklist]
### Misc
- [x] Back-blog Ronan Harrington interview from this [draft](https://docs.google.com/document/d/1hMpUa1dbn3u04c8EQUhHX5tCgNT0PvJx_rp5qha7kVU/edit) **Published here: https://lifeitself.org/blog/2021/07/29/interview-ronan-harrington-alter-ego**
- [x] At the bottom of this page: https://lifeitself.org/blog/2021/07/28/adam-brock-regenerate-change: a) Fix link to ecosystem mapping b) Fix link to newsletter signup
- [x] Ditto for https://lifeitself.org/blog/2021/07/20/romy-kraemer-guerrilla-foundation
- [x] Ditto for https://lifeitself.org/blog/2021/07/13/ecosystem-mapping-conversation-4-with-alnoor-ladha
- [x] Ditto for https://lifeitself.org/blog/2021/06/23/conscious-evolution-robert-cobbold
- [x] Ditto for https://lifeitself.org/blog/2021/07/02/richard-d-bartlett
- [ ] Fix visualisations on this page (not showing up properly for me -- see screenshots): https://secondrenaissance.net/vis#visualizing-the-ecosystem-by-topic ❌ **Don't need to do this -- added short blurb re each vis to the main PIP landing page and linked to full report for more detail. Can delete this page.**
- [ ] Move visualizations page for PIP report under pip ... ❌ **I don't see a reason to do that right now**
- [ ] ? Delete the about page (after integrating)? https://secondrenaissance.net/about ❌ **The About page was updated to be a general about page for the 2R project so no need to delete now**
- [ ] ? move directory to a separate page?? **❌  I don't see a reason to do that right now**
```

![Screenshot 2024-04-08 at 14 23 24](https://github.com/life-itself/secondrenaissance/assets/97066487/ab54802f-2a7f-43b4-8f4b-d0775e4d194d)
![Screenshot 2024-04-08 at 14 23 28](https://github.com/life-itself/secondrenaissance/assets/97066487/58f7954b-a53f-47a3-96db-c54bb88cd20a)

```[tasklist]
### Materials to review and integrate
- [x] https://secondrenaissance.net/about
- [x] See list at bottom of https://lifeitself.org/initiatives/ecosystem-mapping
  - [x] Preliminary research interviews **Interviews are linked in Preliminary research interviews section**
  - [x] Alpha Launch, <https://lifeitself.org/blog/2021/10/12/state-of-sensemaking-directory-alpha-launch> **Integrated into current focus section**
  - [x] Mapping for Emergence, <https://lifeitself.org/blog/2021/12/09/mapping-for-emergence> **Quoted and linked in Why map? section**
  - [x] Partnership with IFIS announcement, <https://lifeitself.org/blog/2022/02/10/mapping-an-emerging-ecosystem-partnership-with-the-institute-for-integral-studies>
  - [x] October 2022 mapping update, <https://lifeitself.org/blog/2022/10/25/ecosystem-mapping-update>
- [x] Highlights from interviews https://docs.google.com/document/d/1Z_cc7MCUh69AqqsCZiv46Z7Y-eaez2awpoMSXE_FBG0/edit
```

---

## Extras: what about lifeitself.org/ecosystem

New text for lifeitself.org/ecosystem

- What did we use to have there?
- Do we just want to redirect it?

Why do we want it at all?

What's the KISS approach?

Where do we write about our plans? the overall project? rather than the outputs ...

**Comment by catherinet1** [comment]
NTS: idea: one "report" page which documents the background, motivation, why map etc., similar in format to 2020 page, and links out to mapping site itself, and one "map site" which is similar in format to current ecosystem map site, for people just interested in the ecosystem itself and less in the research background behind it

**Comment by rufuspollock** [comment]
OK, first, good job Catherine on synthesizing all the material.

I think there was a bit of an initial misunderstanding: what i'd thought we were doing was a) relocating (quick) b) updating the 2021 landing page to be more of a report.

This 

Here's the original rough task list:

``` md
- [ ] Change the title to be specific e.g. "PIP for Social Change: Mapping an Emerging Ecosystem of Paradigmatic, Integrative, and Pragmatic Changemakers"
- [ ] Move the names that are currently in the carousel --> 👍 Mention them in intro? e.g. "We sense that a new ecosystem, or ecosystem of ecosystems, is emerging. It goes by many names, e.g. Metamodern, Polycrisis, Metacrisis, Great Transition, Liminal ... etc."  
- [ ] Change PIE to PIP
- [ ] Frame the visualizations better ...
- [ ] Not clear what Discover and Explore buttons mean -- change to e.g. "Read more" and "Explore the organisations"
- [ ] ? move directory to a separate page??
- [ ] Integrate /about/ page as introduction / motivation
- [ ] Have better headings
- [ ] Published date in the hero section (with maybe updates info e.g. published Oct 2nd 2021 - updated Feb 2022)
- [ ] Correct authors to just be Life Itself ...
- [ ] Add Interviews section - blurb and links to published interviews
- [ ] Move profiles and fix links in profiles
```

Where I'm at.

- First, because it was difficult for me to understand where we were at: I consolidated the 3 main content sources (current landing page, new report page, about page) into one google doc here https://docs.google.com/document/d/1Q5GOjaBJB1WHPojZnvH3FApAYsKb6AYrnvOk2c6ABr0/edit
  - I then attempted to deduplicate / understand what was new / different etc
- I also thought quite a bit about the actual structure of the report and if there was anything we want to add (e.g. a synthesis of key points in an exec summary). Notes on this are in the gdoc

⏭️ Let's review the gdoc together, decide on what is to be done and then we can implement.

**Comment by rufuspollock** [comment]
Discussed and next steps at the top of the https://docs.google.com/document/d/1Q5GOjaBJB1WHPojZnvH3FApAYsKb6AYrnvOk2c6ABr0/edit

**Comment by catherinet1** [comment]
Have updated progress in issue above (see ToC Sketch under "Report" section). Report draft in progress here: https://docs.google.com/document/d/1Q5GOjaBJB1WHPojZnvH3FApAYsKb6AYrnvOk2c6ABr0/edit.

**Comment by catherinet1** [comment]
Draft complete EXCEPT executive summary here: https://docs.google.com/document/d/1Q5GOjaBJB1WHPojZnvH3FApAYsKb6AYrnvOk2c6ABr0/edit

**Comment by catherinet1** [comment]
Next actions:
- [ ] Edit Method section (make shorter and move out most stuff to appendices)
- [ ] Review and integrate comments
- [ ] Exec Summary

**Comment by catherinet1** [comment]
2024-06-04 update: 
- Uploaded PDF of full report (see Acceptance for link)
- Linked via Read full report button in hero section of PIP landing page
- Updated hero section of PIP landing page

**Comment by catherinet1** [comment]
@rufuspollock PIP report and landing page update is now complete, see https://secondrenaissance.net/ecosystem/pip and see previous comment for more detailed update. 

Only thing remaining is redirects (see Tasks tasklist above)

**Comment by rufuspollock** [comment]
FIXED. Did the redirects.
