### ISSUE TITLE
Add analytics (google) for tracking visits

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#25]
When running the site i want to know how many people are visiting what so that i know what is useful

## Acceptance

* [x] Analytics installed **DONE**
* [x] Working (i.e. info showing up in our analytics dashboard)

## Tasks

* [x] Register a new property **DONE: See [new property](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/p289165181/reports/reportinghub?params=_u..nav%3Dmaui)**
* [x] Work out how to do this in next.js **DONE: Follow https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/**
* [x] Do it
