### ISSUE TITLE
[epic] 2nd Renaissance and its Ecosystem Part II (v0.2)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#252]
```[tasklist]
### Major items
- [ ] #258
- [ ] https://github.com/life-itself/secondrenaissance/issues/281
- [ ] https://github.com/life-itself/secondrenaissance/issues/283
```

```[tasklist]
### Unscoped
- [ ] Course section
- [ ] Wiki section
- [ ] Forum
```

```[tasklist]
### Redirects
- [ ] Redirect lifeitself.org/ecosystem/state-of-sensemaking-2020 to new home on secondrenaissance.net
```

**Comment by catherinet1** [comment]
We have 5 user research interviews scheduled: Simon and Alexandre on Thursday 11th, Lisa and Bene on Friday 12th, Cassius on Monday 15th.

Also sent a second message with "last call" for participants in Get Involved and General Whatsapp group chats today so someone else may yet sign up.

cf #264

**Comment by catherinet1** [comment]
User research interviews are complete. 

We interviewed 8 people:
- Lisa Heinrichs (Hub)
- Alexandre Lenoir (Hub)
- Bene (Hub)
- Simon Grant (research community)
- Matthew McCarthy (research community)
- James (General Chat)
- William Rogers (General Chat)
- Cassius Carvalho (General Chat)

Recordings and transcripts are here: https://drive.google.com/drive/folders/1W4mx4BvtZaX888VLxcvpG1x5jzoo6TP

Next step re user research: interview analysis

#281

**Comment by rufuspollock** [comment]
FIXED. this was work from our second ship iteration in April 2024.
