### ISSUE TITLE
2nd Renaissance Landing Page v0.2

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#258]
```[tasklist]
### Tasks
- [x] Rework hero and images on front page with @shiweiart **✅2024-04-08**
- [ ] Sort out hero section to indicate broad range
- [ ] Update hero section to reference/acknowledge some of key concepts/activities so that people coming know we are aware of them (from feedback we got)
- [ ] Add the posts section back in
- [ ] Fix the signup to actually be to the course
- [ ] BONUS Add a CTA ...
- [ ] BONUS: add a newsletter signup
```

## Rufus: What more do we need for hero section?

- Jot down some ideas? Or just implement
- Share them with people and see what they think
- Ideas
  - Have some kinds of words fixed or floating about in the background on the home page
  - have some side notes or some kind ...

## Brainstorm

- [ ] Add an intro section to 4 beliefs framing what that is about
- [ ] Have "more info" section on each of the statement e.g. show the diagram about core beliefs of modernity, show detail on examples of crises with further info ...
- [ ] Add additional 4/5th section on "strategy" to get to "awakening society/second renaissance" (eight fold path ...)
- [ ] Allow people to vote on their agreement with each statement on a sliding scale and leave a comment

## Posts stuff

# 2024-03-19 - Content links/info

### Overview of ecosystem names

Title: Many names, one ecosystem?
URL: https://ecosystem.lifeitself.org/wiki
Description: An overview of the different names and terms that the Second Renaissance ecosystem is associated with
Type: wiki page

### Overview of related mapping efforts

Title: An Overview of Second Renaissance Ecosystem Mapping Efforts
URL: https://ecosystem.lifeitself.org/wiki/overview-mapping-efforts
Description: An overview of different efforts to map the Second Renaissance (or closely related) ecosystem(s)
Type: wiki page

### Emergent Power report

Title: Emergent Power: Key Challenges and Capacities for Change Agents of a Second Renaissance - a new report
URL: https://lifeitself.org/blog/emergent-power-report-2024
Description: A report on key challenges and capacities for change agents of a Second Renaissance
Type: blog post

### Second Renaissance Intro Course

Title: Second Renaissance Introductory Course
URL: https://lifeitself.org/second-renaissance
Description: A course introduction to the idea of the Second Renaissance, covering the idea of views and values as "foundations" of our societies, cultural paradigms and their role history, the birth and decay of modernity, and what comes next
Type: web page

### Joseph Henrich podcast

Title: Joseph Henrich and the Emergence of a (Rigorous) Culturology
URL: https://lifeitself.org/podcast/joseph-henrich-and-the-emergence-of-culturology
Description: A podcast episode where Rufus talks with Joseph Henrich about study of cultural evolution 
Type: podcast episode

### Sylvie talking about the 2R

Title: Are We Experiecing The Second Renaissance? with Sylvie Barbier
URL: https://lifeitself.org/blog/2023/05/19/sylvie-barbier-second-renaissance
Description: Video in which Sylvie shares about her upcoming book "Second Renaissance" and its connection to Life Itself's vision for a radically, wiser, weller world
Type: podcast episode

### Need in following format

```javascript
const posts = [
  {
    title: 'Boost your conversion rate',
    href: '#', // link to post
    description: 'Illo sint voluptas. Error voluptates culpa eligendi. Hic vel totam vitae illo. Non aliquid explicabo necessitatibus unde. Sed exercitationem placeat consectetur nulla deserunt vel. Iusto corrupti dicta.',
    imageUrl:
      'https://images.unsplash.com/photo-1496128858413-b36217c2ce36?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3603&q=80',
    date: '2020-03-16',
  },
  // More posts...
]
```

**Comment by james-baker** [comment]
`const posts = [
  {
    title: "Many names, one ecosystem?",
    href: "https://ecosystem.lifeitself.org/wiki",
    description: "An overview of the different names and terms that the Second Renaissance ecosystem is associated with",
    type: "wiki page",
    imageUrl: "",
    date: "",
  },
  {
    title: "An Overview of Second Renaissance Ecosystem Mapping Efforts",
    href: "https://ecosystem.lifeitself.org/wiki/overview-mapping-efforts",
    description: "An overview of different efforts to map the Second Renaissance (or closely related) ecosystem(s)",
    type: "wiki page",
    imageUrl: "https://ecosystem.lifeitself.org/assets/Screenshot%202024-03-12%20at%2011.31.50.png",
    date: "2024-03-11",
  },
  {
    title: "Emergent Power: Key Challenges and Capacities for Change Agents of a Second Renaissance - a new report",
    href: "https://lifeitself.org/blog/emergent-power-report-2024",
    description: "A report on key challenges and capacities for change agents of a Second Renaissance",
    type: "blog post",
    imageUrl: "https://lifeitself.org/assets/images/blog-24-02-26.jpg",
    date: "2024-02-26",
  },
  {
    title: "Second Renaissance Introductory Course",
    href: "https://lifeitself.org/second-renaissance",
    description: "A course introduction to the idea of the Second Renaissance, covering the idea of views and values as 'foundations' of our societies, cultural paradigms and their role history, the birth and decay of modernity, and what comes next",
    type: "web page",
    imageUrl: "https://i.ytimg.com/vi/TtOdxV326-Y/maxresdefault.jpg?sqp=-oaymwEoCIAKENAF8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYVSBlKF8wDw==&rs=AOn4CLAJNslZOb2pVQvR8B07jPC-1vubIg",
    date: "",
  },
  {
    title: "Joseph Henrich and the Emergence of a (Rigorous) Culturology",
    href: "https://lifeitself.org/podcast/joseph-henrich-and-the-emergence-of-culturology",
    description: "A podcast episode where Rufus talks with Joseph Henrich about study of cultural evolution",
    type: "podcast episode"
    imageUrl: "https://i.ytimg.com/vi/vYzOr7l-U20/sddefault.jpg",
    date: "2022-11-24",
  },
  {
    title: "Are We Experiecing The Second Renaissance? with Sylvie Barbier",
    href: "https://lifeitself.org/blog/2023/05/19/sylvie-barbier-second-renaissance",
    description: "Video in which Sylvie shares about her upcoming book 'Second Renaissance' and its connection to Life Itself's vision for a radically, wiser, weller world",
    type: "podcast episode"
    imageUrl: "https://lifeitself.org/assets/images/the-second-renaissance-sylvie-barbier.png",
    date: "2023-06-03",
  }
];`

**Comment by james-baker** [comment]
Meta: had an LLM do most of the grunt work. I found some appropriate images, but left a few dates and images as empty strings as I didn't see trivially easy data to grab.

I left in "type", delete it if you don't want it?

**Comment by rufuspollock** [comment]
FIXED / WONTFIX / INVALID. This is now out of date. We did some work and this got superseded by developments. Latest work on this is in #303
