### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#26]
Let's set up some jest tests esp for the data processing

## Acceptance

* [x] `yarn test` runs the jest unit tests

## Tasks

* [x] Research options **See e.g. https://nextjs.org/docs/testing. Note that we may only use jest for etl testing for now so don't need for the site**
* [x] Install jest
* [x] Have at least one basic test
