### ISSUE TITLE
[epic] Consolidated database for app with scripted ETL process

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#27]
## Acceptance

* [x] We have a consolidated database of orgs **DONE. See `data/` folder**
* [x] including screenshots - see #76 

## Tasks

* [x] Get agreed metadata structure **DONE. See [Org Metadata sheet](https://docs.google.com/spreadsheets/d/1sotA3Cm79B1te4ooMQvPk6OHdaxZwnDB2VRLtfQAuRE/edit#gid=106528583)**
* [x] Automate retrieving data from google spreadsheet (with command line) so we can build from source repeatedly (rather than copy and paste)
  * [x] orgs => cache in data/cache/orgs-spreadsheet.csv
  * [x] activity
  * [x] topic
* [x] convert convert this to standard structure and store in main db directory                                          
* [x] scrape metadata and screenshots #23 and #76
* [ ] ~~merge scraped info~~ **WONTFIX. Given varying quality of extracted info always need a manual curation step so i don't think this is possible**
* [x] Tests for the above **WONTFIX. See previous item**
