### ISSUE TITLE
Ecosystem landing page update: hero, list of directories, rosetta stone, 3 layer diagram

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#276]
Pitch: https://github.com/life-itself/comms/blob/main/pitch/2413%20Ecosystem%20section%20on%202R.md

## Acceptance

- [x] Updated ecosystem mapping landing page **Updated version now at secondrenaissance.net/ecosystem**
  - [x] Set out fact there is an emerging ecosystem
  - [x] Key info like "synonyms" / rosetta stone **Matt's map is on page, and names/related efforts overview work is listed in key resources section**
  - [x] Highlight our most mature/recent/consolidated mapping efforts **In mapping projects section**
  - [x] List previous efforts by ourselves (? and others) **In key resources and mapping projects section**

## Tasks

- [x] Draft text/narrative **See "short version" here: https://docs.google.com/document/d/1GwSlpK_E9tCAxpUKxY64avK3LhD4BjdHK-Y1vgaGNK0/edit**
- [x] Mockup **Here: https://app.excalidraw.com/l/9u8crB2ZmUo/4BYzkguswWF**
- [x] Transfer to markdown page /ecosystem **Rufus and Mohammed showed Catherine how to use codespaces and HTML+Tailwind**
- [x] Final bits and pieces
  - [x] What does it look like button --> Matt's map
  - [x] Is Matt's map the final version? **2024-05-06 Still draft version -- Matt and Rufus working on it this week and will try to incorporate below feedback.**
    - [ ] Can we fix small font colour? (really similar to land colour, very hard to read)
    - [ ] Would also be nice if sea/waterway names could be easier to read
  - [x] Fix/finish Matt map caption ❌ **For now flag this is draft and when final version is complete later this week put up final version with caption and link to write-up. Created new issue #298.**
  - [x] Learn more button: add link
  - [x] Add an image to gaining traction section? e.g. screenshot of PIP profiles page, or circle packing viz
  - [x] Get rid of button in const But
  - [x] Get rid of button in Mapping section
  - [x] Underline emphasis in Mapping section
  - [x] Fix link to glossary in key resources
  - [ ] Shall we update PIP page from pip-2021 to pip now? ❌ **Do this as part of #249. Flagging that I used the /pip link instead of /pip-2021 in link on this page as Rufus said we will use /pip as the final URL eventually.**
- [x] Replace ecosystem with ecosystem-new **Rufus did this**

**Comment by catherinet1** [comment]
FIXED. Ecosystem mapping landing page updated here: https://secondrenaissance.net/ecosystem. For now, contains draft version of changemaking ecosystem map, to be replaced by final version of graphic in #298.
