### ISSUE TITLE
Second Renaissance User Research

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#281]
## Acceptance

- [x] https://github.com/life-itself/ecosystem/issues/264 **8 interviews scheduled from Hub (Alexandre Lenoir, Lisa Heinrichs, Bene) and LI Whatsapp groups (Simon Grant, Matthew McCarthy, William Rogers, Cassius Carvalho, James)**
- [x] Prep interviews **Offers slides [here](https://docs.google.com/presentation/d/12eflAeWylkN23IZmWlu6mSiONdC5yZYouj_OK5TrzfA/edit#slide=id.g2cb31172735_0_0); v2 questionnaire (for Mon 15th interviews) [here](https://docs.google.com/document/d/1StKrFLbNUu4NOClP4zbmv0EMdPDpcEUMwOyz_n3g4Fs/edit); [DEP] v1 questionnaire (for Thu/Fri 11th-12th interviews) [here](https://docs.google.com/document/d/1SibGD-zbIE1JdhNyN_3wUF0Oi_Q8mIuiF_Z3NO0J4O4/edit?usp=drive_link)**
- [x] Conduct interviews **2024-04-15 Completed 8 interviews. Recordings and transcripts are [here](https://drive.google.com/drive/folders/1W4mx4BvtZaX888VLxcvpG1x5jzoo6TPN)**
- [ ] Analyse interviews
- [ ] Write up key learnings 
  - [ ] BONUS: if there are learnings which could be relevant to a wider audience, share, e.g. blog post?

## Tasks

- [x] Write a little blurb/framing to say to interviewees at the start (e.g. emphasise gut reactions and feelings/impressions are valuable, want them to interact with the site as they would organically, not asking for advice/suggestions. No need to be helpful or nice.) **See template with instructions and questions here: https://docs.google.com/document/d/1SibGD-zbIE1JdhNyN_3wUF0Oi_Q8mIuiF_Z3NO0J4O4/edit**
- [x] Recruit minimum 5 interviewees **8 interviewees recruited**
- [x] Conduct interviews **interview notes can be found here: https://drive.google.com/drive/folders/1AvYzvEcZCFTkOmoC1ugyYewZtVg_wzYw**
- [x] Create and populate capture sheet **Capture sheet created https://docs.google.com/spreadsheets/d/11p7Qj3DwZIr8tAQ_0hEnsURNz3CNtDqCymoVlq5Rtho/edit#gid=0**
- [x] Draw out key patterns, pain points and conclusions **See https://docs.google.com/document/d/1rh0C1A2ENg5zWpS_ftTGuaaYut_4CEKuM99EwdoI21w/edit**

## Issue tree (rough)

- How many people do we want to recruit? **:key: 5-10 people**
- Who are we targeting? What kind of (mix of) people?
- What is the request? **40-min user research interview...** 
- When do we want to do the user research interviews? **:key: Ideally end of next week, so that we can review and integrate feedback at the beginning of the next week**
- Do we want to offer test users something in return?
- Where are the materials from 2022 user research interviews? **:key: Recordings and notes here: https://drive.google.com/drive/folders/1l2Hex2Vasfqrwli5U9K30hZcWSWPW0wb**
- What do we want from these interviews? **Gut reactions, rather than advice/suggestions/trying to be helpful"**
- What specific questions are we seeking responses to? What do we want to know/find out?

**Comment by rufuspollock** [comment]
FIXED. We completed the research and got useful feedback.
