### ISSUE TITLE
[epic] Stub Working Example (i.e. v0.1)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#3]
Get a basic working site that we can look at and play with.

Working example = front page plus org profile page

## Acceptance

* [x] Skeleton site live online **DONE. https://ecosystem.lifeitself.us**
* [x] Front page with list of orgs **DONE. https://ecosystem.lifeitself.us**
* [x] Profile page for org with minimal info **DONE. See e.g. https://ecosystem.lifeitself.us/@alter-ego

## Tasks

* [x] Skeleton site
* [x] Pull data from Google Spreadsheet [Ecosystem DB](https://docs.google.com/spreadsheets/d/1sotA3Cm79B1te4ooMQvPk6OHdaxZwnDB2VRLtfQAuRE/edit#gid=678155612) 
  * [x] Retrieve the data - follow this excellent walkthrough https://andreaskeller.name/blog/nextjs-google-sheets-cms or https://fireship.io/lessons/google-sheets-database-nextjs/
  * [x] Cache locally so we can reuse for profile pages, front pages etc
* [x] Profile page
* [x] Front page
* [x] Deploy - using vercel or even just local build **~~DEPLOYED using vercel. https://ecosystem-one.vercel.app.~~ 11 Sep: this is broken now as not on their paid plan. Tried github pages. Also broke as not on paid plan and needed for private domains. Trying netlify**

## Analysis

```
/    # front page
/@...      # org or person page ...
/about.   # from markdown locally
```
