### ISSUE TITLE
Scrape (full) textual contents from sites (eg. for word cloud or presentation)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#30]
When analysing sites or the whole ecosystem I want the full raw textual content so that i can analyse it (automated topic generation) or visualize it (e.g. wordcloud)

## Tasks

* [ ] Download textual content from sites
  * [ ] https://github.com/luin/readability
  * [ ] Can do raw text extraction using apiflash - https://api.apiflash.com/v1/urltoimage?access_key=0633900f9b8d453191b8deef9dd3e910&extract_text=true&no_cookie_banners=true&url=https%3A%2F%2Flifeitself.us&response_type=json
  * [ ] Could this ourselves given how simple it is (and the types of website we are scraping - i.e. not a lot of ads and other junk)
