### ISSUE TITLE
Map of Paradigmatic Changemaking Ecosystem (level 1/2 map)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#302]
## Acceptance

```[tasklist]
### Map itself
- [x] Map of the space level 2 (with minor level 3 and context of level 3) **🚧2024-05-13 nearly there**. UPDATE: **✅2024-05-15 v1 is done https://drive.google.com/drive/u/0/folders/18r_aM33-HjjrNj5Ti_iL4TOgwgNV_vg3**
```

## Tasks

```[tasklist]
### Tasks
- [x] Relayout the map with the inner-outer axis **✅2024-05-08**
- [x] Review regions and get suggestions for stuff to add **✅2024-05-10 input from James and Danielle and others**
```

### Inner-lands of the west

- [ ] Relational practices
- [ ] Psychedelics
- [ ] Personal Healing
- [ ] Collective Liberation
- [ ] Sacred and Ritual
- [ ] Spiritual and Contemplative Traditions

### Outer-lands of the east

- [ ] Deep adaptation
- [ ] Pop-up Communities
- [ ] Web3
- [ ] Open Source
- [ ] Intentional Community
- [ ] Ownership & Governance
- [ ] Open Science
- [ ] Alternative Politics
- [ ] Alternative Economics
- [ ] Techno-solutionism
- [ ] Regenerative Alternatives
- [ ] Alternative Education
- [ ] Effective Altruism
- [ ] Rationlist

### Sensemaking

- Integral
- Wisdom
- Metamodern
- Metacrisis

### Islands and archipelagos

- Critique of Power
- Vibes

# Consolidated feedback for action 2024-05-13

### General things re the map (not positioning)

- [x] Title: Second Renaissance Changemaking Ecosystem
- [x] Maybe something like: "Ye Olde "
- [x] Logo: Life Itself [logotype] and friends
- [x] Add a version somewhere? ❌

### Stuff to add

Sensemaking island
    
- [x] Add Second Renaissance (?)
- [x] Liminial Web / Limicon (in west part of Metamodernism)
- [x] Brendan Graham Dempsy / Skymeadow (in Metamodernism)
- [x] New Republic of the Heart (in Integral, near Spiritual)
- [x] Emergent Commons (in Metacrisis next to Rebel Wisdom)
- [x] UTOK (Gregg Henriques) near Vervaeke (in... somewhere in Sensemaking island)
- [x] Tyson Yunkaporta ...

Inner development Island

- [ ] Add "Adult Development" as topic
- [x] Inner Development Goals => Dev mountains (on integral / wisdom side)
- [x] Robert Kegan
- [x] Lectica, Theo Dawson
- [ ] NOT FOR NOW
  - [ ] Piaget
  - [ ] Kohlberg ...
  - [ ] Jonathan Reams ...
  - [ ] (?) Kurt Fischer

#### Inner lands of the west

Relational practices
 
- [x] Collective Presencing [Ria Baeck] (in Relational Practices)
- [x] Evolve / Emergent Dialog (Steininger and Debold)
- [ ] Maybe
  - [ ] Liminal Space Agency (in Relational Practices)
  - [ ] Communication Dojo (in Relational Practices)

Sacred and ritual [MAYBE]

- [ ] Sacred Ground (in Sacred and Ritual, near RP)
- [x] River Kenna [Wilderless] (in Sacred and Ritual, near mythopoetics) - https://innerwilds.quest

#### Lands of the east

Ethical tech

- [x] Add ethical tech island?
- [x] Center for Humane Tech (+?? Tristan Harris)
- [x] Joe Edelman and his new org
- [x] ?? Concepts Open Source, Open Knowledge ..., Wise AI

Alt education

- [x] Global Bildung Network (in Alternative Education)  Bildung project (* Lene Andersen)
- [ ] (?) Springboard - ?Microcolleges - education?
- [ ] Commonweal (? or near DDS)

Regen

- [x] Doomer Optimism (in Regen, near Ecology)
- [x] Joe Brewer ...

#### Vibes island

- [x] Make a bit smaller?
- [x] Visa [Visakan Veersamy, Friendly Ambitious Nerds] (in Vibes near TPOT)
- [ ] Post-rat island nearby or ... "Postrationalists" could go on Vibe island sticking out toward Rationalism

#### Intentional communities

- [x] Add Praxis Hub

#### Region notes

- [x] Techno-optimism becomes Ethical tech
  - [ ] Maybe techno-optimism becomes a concept-name right on the edge of it ...
- [ ] ?? Add "Mountains of Development" in center of sensemaking island - not  region per se (+ ?? Crevasse of "stage theory debates")
- [x] Web3 really wants to touch Alt Economics IMHO

#### Seas, ferries etc

Rufus random ideas ...

- Polycrisis sea(s) on the eastern side
  - Climate crisis
  - AI Alignment
  - Inequality crisis
  - Culture wars ...

### Questions / issues

- [ ] Turquoise Sound - Dyer Global
- [ ] Do we have philanthropy? If we do just sticking in somewhere ... Would def stretch off map ...
  - Transition Resource Circle (*Alnoor Ladha + ...)
  - Omidyar (Belonging)
  - Fetzer??
  - One Project (on eastern sides)
- [ ] Do we add systems thinking land somewhere on east
  - TheoryU and Peter Senge ...
  - Systems thinking
- [ ] Famous ICs? Findhorn, Tamara (near edge of map)
- [ ] Intentional communities and DDS and Alt education are connected ... (intentional communities really want their own land ...). Dev mountains (or around DDS?) or ...
  - [ ] Example: Bildung project (where does it go ...) 
- [ ] ? "Psychotherapy" as a sub-region of Personal Healing
- [x] Psychedelics should not touch Collective Liberation (so slide it west). I think Sacred and Ritual wants to go up to where Psychedelics is currently. Joanna Macy is close to personal healing, Eisenstein close to Liberation.  MAYBE this region itself wants to disappear into the other regions
- [ ] List of potential "regional pockets" in a list somewhere (not on map per se?)
  - Toronto ...
  - North carolina ...
  - Stockholm
  - Bergerac
- [ ] Have Gebser - do we add Jeremy Johnson (?) (near Gebser?)
- [ ] Denizen https://www.becomingdenizen.com/orient

#### ????

- [ ] Adam Wright - who is this (?)
- [ ] (?) Luis Mojica (in Personal Healing)

[Podcasts] - do they have a special area??

- [ ] The great simplification, Nate Hagens (??)
- [ ] Entangled world
- [ ] Conscious Evolution??

# Feedback (just for collection - not to act on)

## General points / discussion

Matt

- [x] What are thoughts on the LI logo by compass rose? **💬2024-05-07 Rufus: i'd say it gets a bit lost atm. suggest put "by Life Itself and friends" under the title if we can or we put it somewhere more obvious and visible e.g. along the bottom**

## Rufus notes

Immediate stuff

- Logo (Life Itself, Cohere+, EC?) **EU logo is essential, Cohere+ logo is optional (if this is to be a Cohere+ deliverable). Co-funded by EU logos are in this [folder](https://drive.google.com/drive/folders/1nyimQIDdysB6xRITCZZUJsQ3oMIt771A).**
- Change name: Map of Paradigmatic Changemakers

Big stuff: Putting island towards the center and using 4 quadrants to organize the map

- ❓ is this changing Or this is a second version with the island in the center
- "Integral Island" as name for central part
- Using AQAL 4 quadrants to organize the map
  - Centre left island is currently Inner-I (so that moves to top left)
  - Can split center right continent into Outer-I (e.g. open science, open source, techno-solutionism etc) and outer-we (more systems change)
  - Need an island for the "we" stuff. some of center left island extends down there.
- [x] Is the AQAL quadrant idea something to explore for a future version or something for now? **✅2024-05-09 we can use it a *bit* now**

Open questions

- [x] Concerned about the "head-y-ness" of the island. want more practice stuff. Not sure though really about how to do that. Integral Island definitely is the closest to having a *theory* of change (if not a *practice* of change)
  - [x] What practical stuff is it felt that is missing from the island? Is this elsewhere on the map already, or new? **✅2024-05-09 no change for now**
- [x] Adding systems change e.g. theory-u type stuff somewhere.

## Catherine notes

1) Can we easily change the colour of the small font (of e.g. Spiral Dynamics and stage theory) so that it is more legible? I find those bits very difficult to read atm and think that would make a worthwhile difference. (Minor point: i think it would also be nice if the sea/waterway names were easier to read e.g. bigger or bolder text or stronger colour contrast)
2) Can you send me a high-res version of the final graphic to put on the ecosystem landing page and also its write-up/publication (which i assume we will post on substack, but for now is in draft form here: https://secondrenaissance.net/publications/map-paradigmatic-changemakers) i think the one currently on the landing page is not the best atm. i cant remember where elisa and/or I got this one from.
3) Hanzi Freinacht is misspelt as Frienacht

# Map Versions

## 2024-04-17 - first fairly complete version

![image](https://github.com/life-itself/second-renaissance/assets/180658/9aa69591-bd1a-4fab-a65d-b1b4a7d17ded)

**Comment by rufuspollock** [comment]
FIXED.
