### ISSUE TITLE
Soft Launch May 2024

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#303]
```[tasklist]
### Tasks
- [ ] #301
- [ ] https://github.com/life-itself/second-renaissance/issues/304
- [ ] #302
- [x] https://github.com/life-itself/second-renaissance/issues/305
- [ ] https://github.com/life-itself/second-renaissance/issues/306
- [x] Newsletter setup
- [ ] https://github.com/life-itself/second-renaissance/issues/249
- [x] About page **✅2024-05-19 see https://secondrenaissance.net/about**
- [x] Announcement - see below
- [ ] https://github.com/life-itself/second-renaissance/issues/309
```

## Sub-items

```[tasklist]
### Announcement
- [x] Draft announcement e.g. blog posts, socials, message to lists, to friends and family **See draft here: https://docs.google.com/document/d/1KHGd5ram5KCx4A1dQS2Kwv6IFz34BclYGMfCS6ZfWFg/edit**
- [x] Publish on Life Itself blog
- [x] Publish to second renaissance substack @laurenwigmore
- [ ] ...
```

```[tasklist]
### Newsletter / Blog setup
- [x] Create a substack **✅2024-05-13 https://secondrenaissance.substack.com**
- [x] Tweak config e.g. no prompt signup screen to see posts (?)
- [x] Remove default empty post **✅2024-05-19 unpublished**
- [ ] Migrate some content over e.g. some major publications like the intro ??
- [x] Subscribers from Life Itself
```
```[tasklist]
### Misc
- [x] 🔥 Resize map and add to the ecosystem page **✅2024-05-19 converted to webp (500k) and added to page**
- [x] Add chat to navbar **✅2024-05-29**
- [x] Create a proper contact page with suggestions to email hello@secondrenaissance.net or join discord **✅2024-05-29**
- [ ] Update redirect from ecosystem.lifeitself.org to go to `/ecosystem/pip`
- [ ] Redirect lifeitself.org/second-renaissance to here
- [ ] 🧊 Remove unused images for homepage etc
- [ ] 🔥 Sort out `/glossary` whose list of terms link to old wiki that is now moved to actual wiki
- [ ] 🧊 Set Favicon (sunrise emoji) 🌄
- [ ] Update analytics for new url
- [ ] Add Get Involved link and page (say we welcome participation and suggest join discord as first step)
```

```[tasklist]
### Future / Bonus
- [ ] Add map on its own page ...
- [ ] Blog post about the map (for the future)
- [ ] Second renaissance name post ...
```

# ///// Day to Day

```[tasklist]
### 2024-05-20
- [x] Refactor this issue to split out major sub-stacks to own issue
- [x] Review drafted/published about page **✅2024-05-20 and revised**
- [ ] Review and finalize announcement text
```

```[tasklist]
### 2024-05-20 - Next 24h
- [ ] Wiki barn-raising date @asimong and james
- [x] Improvements to CTA (at bottom - and is there one at the top) @james
- [x] Rufus to finalize announce
- [x] Lauren to edit front page text
```

```[tasklist]
### 2024-05-21
- [x] Finalize announce (and hence about)
- [x] Finalize front page
```

```[tasklist]
### 2024-05-29
- [x] Modify James and other people's titles on about and announce
- [x] Release the announce
```

**Comment by catherinet1** [comment]
The draft announcement post that I wrote is in this issue #295 cc @laurenwigmore. It was framed more as announcing a new newsletter but may be helpful material for drafting a broader announcement for this soft launch.

**Comment by rufuspollock** [comment]
FIXED. All done.
