### ISSUE TITLE
2R Preview Webinar Set-up

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#309]
On Thursday 30th May 7pm CEST we're hosting a special webinar to offer a first look at our new "Second Renaissance" project.

Intention: do a preview, get feedback and informally launch
Overall aim of all launch actions: to get people to come to 2R; to know what it's about, and share, and contribute/get involved.

## Acceptance

- [x] Webinar hosted
- [x] Webinar recording live on YouTube

## Tasks
 - [x] Confirm date and time - Thursday 30th 7pm CEST
 - [x] Set up event (zoom or lu.ma) _decided to trial lu.ma in case useful moving forward_ event link: https://lu.ma/4cb45aqu
- [x] Invites sent
   - [ ] To advisors & curators
   - [x] To LI community whatsapp - Thursday 23rd May
   - [x] Mailout and substack post? 
   - [x] Twitter
   - [x] Instagram
   - [x] LinkedIn event
 - [ ] Official announce post live (on Wed 29th) 
 - [ ] Included in May newsletter and link

### Text

*Second Renaissance preview webinar*

Next week we're hosting a special webinar to offer a first look at our new "Second Renaissance" project.

It's introduction and guide to this moment of civilizational crisis and awakening -- and the emerging ecosystem related to it.

Register here: lu.ma or just zoom sign up ...

*More about the project*

The Second Renaissance project provides an introduction and guide to this moment of civilizational crisis and awakening – and the emerging ecosystem related to it.

It aims to provides an accessible entry-point – a gateway – for people to discover and make sense of this emerging moment and field. A bit like a curated art gallery for an emerging area of art.

We’re motivated by the increasing need to present these ideas and emerging ecosystem to others in an accessible way. Our experience has shown that the space can be difficult to discover, engage with, and make sense of.

For instance, there are many new terms associated with it: Metamodern, Metacrisis, Integral, Teal, Liminal Web, GameB, Regenerative, and more. This can make it confusing: it’s hard to understand what they all mean, how they all fit together – even if they point to the same thing or not. Overall, there is a lot of information and content out there, comprising many perspectives and approaches. Navigating all of this can be overwhelming and bewildering.

The project offers a simple framing narrative, along with introductions to key ideas, as well as a wiki and forum for community contribution and conversation.

**Comment by rufuspollock** [comment]
FIXED. This is all done 😄
