### ISSUE TITLE
Finalize content for v1 alpha

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#31]
## Tasks

* [x] Finalize list of orgs that are "in" and "out". I would err to keeping orgs in but things like "thehum" are IMO too minor to be there and unbalance it a bit @theo-cox **First pass done**
* [ ] ~~Review any submissions from google form @theo-cox~~
* [x] Reapply topic and activity to orgs using id (rather than full name) @juliedayot
  * [x] Replace Inner Development with development (previously no corresponding id for Inner Development) **sorted** @juliedayot 
* [x] Making spelling corrections @juliedayot 
  * [x] Sort the mix of UK versus US Enflish in the 'about' page **sorted** @juliedayot 
  * [x] Fix spelling mistakes in the 'profiles' page (‘becomes’ => remove a ‘s’) @rufuspollock 
* [x] Find email, facebook, twitter and Instagram urls for Y and YY organisations @juliedayot  **sorted**  
* [x] Finalize key image for orgs and correct the broken ones (and then message rufus so he can archive into cloudinary) @juliedayot **sorted**  
  * [x] (?) Answer #21 
  * [x] Decide what to do when logo differs from logo cached @juliedayot 
  * [x] Deal with broken and missing links @juliedayot 
* [x] #18 - plus add new dimensions if appropriate
* [x] Check activity well applied (again maybe adjust or reduce set down - or create e.g. 3 super categories)

Maybe?

* [ ] Consider adding curated images where logo contains too much text
* [ ] Apply tags e.g. integral, metamodern etc
* [x] Update about page to reflect final content e.g. in the announce **Did it on front page in the end**
