### ISSUE TITLE
HTML image map for 2R ecosystem map

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#311]
## Acceptance

- [x] Have coordinates and links for all individuals and organisations **In here: https://docs.google.com/spreadsheets/d/1UCNiz4PITIUw3jI-nqAHlOJF7VEHitB36NSE9o0PhCM/edit?gid=0#gid=0**
- [x] Clickable HTML image map of 2R ecosystem (clicking on organisations' and people's names goes to a relevant link) is live **Working HTML image map is here: https://secondrenaissance.net/map/ecosystem_map.html**
- [x] Clickable HTML image map replaces the non-interactive version on the site **HTML image map is linked from https://secondrenaissance.net/map (click anywhere on image, or on link in caption)**
- [x] Blog post to share this new version **Did not do a blog post, but posted on: WhatsApp general chat, LinkedIn, Twitter, Discord + noted for inclusion in LI January newsletter**

## Tasks

- [x] Ask for help in Discord server **2024-06-05 rufus asked for help with creating HTML image map in Discord server and aashay volunteered 🙏**
- [x] Get coordinates for points on map **Spreadsheet of names, coordinates, and links here: https://docs.google.com/spreadsheets/d/1UCNiz4PITIUw3jI-nqAHlOJF7VEHitB36NSE9o0PhCM/edit?gid=0#gid=0**
  - [x] Test run **aashay found this tool to generate map coordinates: https://www.image-map.net/ and did a small set of points. catherine double checked by running code through HTML compiler https://onecompiler.com/html/42fzbxzwp 👍** 
  - [x] Make any adjustments **Use target="_blank" instead of target="_self" so that the links open up in a new tab. aashay decided to get rid of titles as kind of repetitive and unnecessary**
  - [x] Do the rest **aashay's finished [spreadsheet](https://docs.google.com/spreadsheets/d/19ftwRnxNV-3WEb_rZGMXJPzoxKWHkJwfiTd13qYe5MI/edit?pli=1&gid=0#gid=0). Made a copy and saved in GDrive here: https://docs.google.com/spreadsheets/d/1UCNiz4PITIUw3jI-nqAHlOJF7VEHitB36NSE9o0PhCM/edit?gid=0#gid=0**
- [x] Check coordinates **2024-07-02 CT ran code through [HTML compiler](https://onecompiler.com/html) and scanned map to check correct areas are clickable and scanned spreadsheet to check links -- looks good 👍**
- [x] Create clickable map **HTML image map only: https://secondrenaissance.net/map/ecosystem_map.html. On page in iframe: https://secondrenaissance.net/ecosystem_map.**
  - [x] Compile code for HTML map **Pasted below**
  - [x] Implement
  - [x] Troubleshoot **See comments for more detail**
- [x] Publish
  - [x] Replace non-clickable version at https://secondrenaissance.net/map ?
  - [x] inc. acknowledgement of volunteer contribution **Acknowledged in newsletter and social media posts**
- [x] Share
  - [x] Write blurb **In here: https://docs.google.com/document/d/13u7Q3a46yEENXBjok0XyuM5mmhr0e7W6Q9zxvOmxrHg/edit?tab=t.0**
  - [x] LI January newsletter **Noted for inclusion in https://github.com/life-itself/community/issues/1145**
  - [ ] 2R newsletter?
  - [x] Twitter **Tweeted on 3 Feb 2025**
  - [x] LinkedIn **Posted on 3 Feb 2025**
  - [x] WhatsApp **Posted on 3 Feb 2025**
  - [x] Discord **Posted on 3 Feb 2025**

### How to publish? - Analysis

Situation: the coordinates were plotted based on a very large image of the map. Therefore, the working clickable HTML image map is very large. There are several options for publishing/displaying the HTML image map.

- Option 1: At the top of https://secondrenaissance.net/map, add something like "Click on the map to explore an interactive version where you can click on names on the map to learn more about them." (Or add to caption instead of at the top.) Clicking on the map takes you to https://secondrenaissance.net/map/ecosystem_map.html. **🔥 Have gone with this**
- Option 2: Have the HTML image map published on the map landing page in an iframe similar to this https://secondrenaissance.net/ecosystem_map. (Would need to resize iframe and update text on this page) 
- Option 3: Replace https://secondrenaissance.net/map with https://secondrenaissance.net/map/ecosystem_map.html as the main map landing page
- Option 4: Resize image (make it smaller) and redo coordinates so that we have a clickable version closer in size to current version displayed on  https://secondrenaissance.net/map (more easily visible at a glance). 
- Aside: Simplify the URL of https://secondrenaissance.net/map/ecosystem_map.html?

**Recommend: Option 1, as then you can get the image overview of the whole map on the map landing page and then click to explore clickable version**

### Context

We want to make the current map clickable by turning it into an html "image map".

This involves creating a list of the places on the map and the coordinates for a box on the map.

See for example view-source:https://slatestarcodex.com/blog_images/ramap.html

So for each thing we want to link we need coords box (probably list this in a sheet and then we can auto generate html)

```
<img id="Map of the Rationalist Community" src="http://slatestarcodex.com/blog_images/ramap.jpg" border="0" width="3292" height="1800" orgWidth="3292" orgHeight="1800" usemap="#ramap" alt="" />

<map name="ramap" id="Map Of The Rationalist Community">
<area  alt="" title="" href="https://groups.google.com/forum/#!forum/vancouver-rationalists" shape="rect" coords="139,559,222,578" style="outline:none;" target="_self"     />
<area  alt="" title="" href="https://groups.google.com/forum/#!forum/lw-seattle" shape="rect" coords="170,627,231,652" style="outline:none;" target="_self"     />
<area  alt="" title="" href="https://groups.google.com/forum/#!forum/lesswrongwaterloo" shape="rect" coords="512,746,589,778" style="outline:none;" target="_self"     />
<area  alt="" title="" href="https://groups.google.com/forum/#!forum/less-wrong-ottawa" shape="rect" coords="602,671,678,692" style="outline:none;" target="_self"     />
<area  alt="" title="" href="https://www.facebook.com/groups/380103898766356/" shape="rect" coords="743,648,810,667" style="outline:none;" target="_self"     />
<area  alt="" title="" href="http://www.meetup.com/Cambridge-Less-Wrong-Meetup/" shape="rect" coords="683,747,756,779" style="outline:none;" target="_self"     />
<area  alt="" title="" href="http://wiki.lesswrong.com/wiki/NYC_meetup_group" shape="rect" coords="571,830,644,875" style="outline:none;" target="_self"     />
```

### Compiled code for HTML map

```
  <img src="/assets/img/ecosystem/second-renaissance-ecosystem-map.webp" usemap="#2r-map">
  <map name="2r-map">
    <area target="_blank" alt="" title="" href="https://lecticalive.org/" coords="1382,641,1562,690" shape="rect">
<area target="_blank" alt="" title="" href="https://innerdevelopmentgoals.org/" coords="1688,875,1815,928" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Robert_Kegan" coords="1261,845,1475,894" shape="rect">
<area target="_blank" alt="" title="" href="https://vibe.camp/" coords="2301,680,2514,724" shape="rect">
<area target="_blank" alt="" title="" href="https://knowyourmeme.com/memes/subcultures/tpot-postrat" coords="2271,743,2393,782" shape="rect">
<area target="_blank" alt="" title="" href="https://www.metalabel.com/" coords="2441,807,2680,845" shape="rect">
<area target="_blank" alt="" title="" href="https://x.com/visakanv?lang=en" coords="2301,607,2373,632" shape="rect">
<area target="_blank" alt="" title="" href="https://x.com/RichDecibels" coords="2519,671,2782,709" shape="rect">
<area target="_blank" alt="" title="" href="https://lifeitself.org/hubs/bergerac" coords="1742,2830,1980,2888" shape="rect">
<area target="_blank" alt="" title="" href="https://www.montaia.com/" coords="1513,3029,1722,3078" shape="rect">
<area target="_blank" alt="" title="" href="https://cabin.city/" coords="2048,3044,2189,3097" shape="rect">
<area target="_blank" alt="" title="" href="https://cityoftelosa.com/" coords="2378,3010,2544,3063" shape="rect">
<area target="_blank" alt="" title="" href="https://www.traditionaldreamfactory.com/" coords="2616,2937,2966,3049" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Occupy_movement" coords="5235,2692,5454,2774" shape="rect">
<area target="_blank" alt="" title="" href="https://rebellion.global/" coords="4963,2959,5289,3042" shape="rect">
<area target="_blank" alt="" title="" href="https://adriennemareebrown.net/" coords="3977,3080,4307,3110" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Bell_hooks" coords="4074,2998,4234,3032" shape="rect">
<area target="_blank" alt="" title="" href="https://shoshanazuboff.com/book/" coords="4263,2944,4502,2983" shape="rect">
<area target="_blank" alt="" title="" href="https://craphound.com/" coords="4244,2842,4482,2886" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Audre_Lorde" coords="4366,3027,4555,3066" shape="rect">
<area target="_blank" alt="" title="" href="https://www.benkler.org/" coords="4574,3061,4778,3095" shape="rect">
<area target="_blank" alt="" title="" href="https://www.ynharari.com/" coords="4754,2896,4915,2964" shape="rect">
<area target="_blank" alt="" title="" href="https://naomiklein.org/" coords="4803,2565,5002,2614" shape="rect">
<area target="_blank" alt="" title="" href="https://davidgraeber.org/" coords="5046,2633,5255,2663" shape="rect">
<area target="_blank" alt="" title="" href="https://chomsky.info/" coords="5308,2871,5454,2944" shape="rect">
<area target="_blank" alt="" title="" href="https://www.soundstrue.com/" coords="7,981,284,1035" shape="rect">
<area target="_blank" alt="" title="" href="https://www.somaticexperiencing.com/about-peter" coords="22,476,202,520" shape="rect">
<area target="_blank" alt="" title="" href="https://drgabormate.com/" coords="488,763,653,807" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Carl_Jung" coords="420,879,571,918" shape="rect">
<area target="_blank" alt="" title="" href="https://plumvillage.org/" coords="445,1059,736,1108" shape="rect">
<area target="_blank" alt="" title="" href="https://www.monasticacademy.org/" coords="882,1343,1295,1397" shape="rect">
<area target="_blank" alt="" title="" href="https://oneearthsangha.org/" coords="843,1545,1232,1594" shape="rect">
<area target="_blank" alt="" title="" href="https://linktr.ee/buddhistgeeks" coords="41,1606,386,1645" shape="rect">
<area target="_blank" alt="" title="" href="https://scienceandnonduality.com/" coords="304,1739,556,1841" shape="rect">
<area target="_blank" alt="" title="" href="https://www.planetarydharma.com/" coords="51,1883,459,1936" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Th%C3%ADch_Nh%E1%BA%A5t_H%E1%BA%A1nh" coords="542,1178,804,1217" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Rob_Burbea" coords="1120,1428,1290,1467" shape="rect">
<area target="_blank" alt="" title="" href="https://psychedelicsociety.org.uk/" coords="90,2162,362,2274" shape="rect">
<area target="_blank" alt="" title="" href="https://www.evolve-world.org/" coords="697,1773,989,1812" shape="rect">
<area target="_blank" alt="" title="" href="https://www.intentionalsociety.org/" coords="542,2099,819,2201" shape="rect">
<area target="_blank" alt="" title="" href="https://www.collectivepresencing.org/author/" coords="838,2109,989,2148" shape="rect">
<area target="_blank" alt="" title="" href="https://advaya.life/" coords="347,2347,503,2390" shape="rect">
<area target="_blank" alt="" title="" href="https://open.spotify.com/show/1OwFblqZ7FIkLSW4rvbJEF" coords="206,2735,498,2779" shape="rect">
<area target="_blank" alt="" title="" href="https://www.joannamacy.net/" coords="66,2434,260,2468" shape="rect">
<area target="_blank" alt="" title="" href="https://charleseisenstein.org/" coords="483,2412,746,2451" shape="rect">
<area target="_blank" alt="" title="" href="https://www.riverkenna.com/" coords="571,2718,756,2757" shape="rect">
<area target="_blank" alt="" title="" href="https://integrallife.com/" coords="2004,1358,2305,1407" shape="rect">
<area target="_blank" alt="" title="" href="https://newrepublicoftheheart.org/" coords="1635,1630,1936,1727" shape="rect">
<area target="_blank" alt="" title="" href="https://integralinstitute.org/" coords="1941,1752,2335,1790" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Sri_Aurobindo" coords="1844,1295,2043,1329" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Jean_Gebser" coords="2208,1285,2378,1319" shape="rect">
<area target="_blank" alt="" title="" href="https://laymanpascal.substack.com/" coords="1854,1460,2072,1504" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Don_Edward_Beck" coords="2310,1479,2456,1518" shape="rect">
<area target="_blank" alt="" title="" href="https://en.wikipedia.org/wiki/Ken_Wilber" coords="2155,1620,2320,1659" shape="rect">
<area target="_blank" alt="" title="" href="https://metamoderna.org/" coords="2840,1411,3146,1465" shape="rect">
<area target="_blank" alt="" title="" href="https://www.limicon2024.com/" coords="2646,1470,2825,1518" shape="rect">
<area target="_blank" alt="" title="" href="https://www.skymeadowinstitute.org/" coords="3054,1650,3306,1693" shape="rect">
<area target="_blank" alt="" title="" href="https://systems-souls-society.com/" coords="2918,1858,3175,1902" shape="rect">
<area target="_blank" alt="" title="" href="https://metamoderna.org/hanzi-freinacht/" coords="2704,1339,2932,1373" shape="rect">
<area target="_blank" alt="" title="" href="https://www.brendangrahamdempsey.com/" coords="2913,1766,3267,1820" shape="rect">
<area target="_blank" alt="" title="" href="https://civilizationresearchinstitute.org/" coords="2733,1985,2991,2135" shape="rect">
<area target="_blank" alt="" title="" href="https://www.game-b.org/" coords="3010,2092,3161,2140" shape="rect">
<area target="_blank" alt="" title="" href="https://emergent-commons.mn.co/" coords="2714,2330,3136,2383" shape="rect">
<area target="_blank" alt="" title="" href="https://www.youtube.com/c/RebelWisdom" coords="2728,2456,3039,2505" shape="rect">
<area target="_blank" alt="" title="" href="https://www.zakstein.org/" coords="2597,1936,2743,1970" shape="rect">
<area target="_blank" alt="" title="" href="https://batesoninstitute.org/nora-bateson/" coords="2519,2033,2709,2063" shape="rect">
<area target="_blank" alt="" title="" href="https://twitter.com/jgreenhall" coords="2927,2165,3102,2208" shape="rect">
<area target="_blank" alt="" title="" href="https://civilizationemerging.com/about/" coords="2466,2233,2718,2325" shape="rect">
<area target="_blank" alt="" title="" href="https://lifeitself.org/" coords="2218,1863,2456,1917" shape="rect">
<area target="_blank" alt="" title="" href="https://secondrenaissance.net/" coords="2150,1975,2412,2087" shape="rect">
<area target="_blank" alt="" title="" href="https://www.whatisemerging.com/" coords="2179,2131,2349,2184" shape="rect">
<area target="_blank" alt="" title="" href="https://www.youtube.com/@johnvervaeke" coords="2121,2233,2364,2335" shape="rect">
<area target="_blank" alt="" title="" href="https://www.unifiedtheoryofknowledge.org/" coords="1824,2364,1985,2417" shape="rect">
<area target="_blank" alt="" title="" href="https://www.youtube.com/@thestoa/" coords="1533,2101,1747,2155" shape="rect">
<area target="_blank" alt="" title="" href="https://twitter.com/bonnittaroy" coords="1926,1907,2121,1956" shape="rect">
<area target="_blank" alt="" title="" href="https://www.peterlimberg.com/" coords="1747,2009,1956,2063" shape="rect">
<area target="_blank" alt="" title="" href="https://channelmcgilchrist.com/" coords="1523,2189,1752,2228" shape="rect">
<area target="_blank" alt="" title="" href="https://www.linkedin.com/in/tyson-yunkaporta-04a9b969" coords="1465,2354,1727,2393" shape="rect">
<area target="_blank" alt="" title="" href="https://www.bayoakomolafe.net/" coords="1484,2432,1718,2476" shape="rect">
<area target="_blank" alt="" title="" href="https://www.bernardokastrup.com/" coords="1858,2281,2111,2330" shape="rect">
<area target="_blank" alt="" title="" href="https://johnvervaeke.com/" coords="2087,2403,2296,2446" shape="rect">
<area target="_blank" alt="" title="" href="https://www.globalbildung.net/" coords="3224,641,3394,787" shape="rect">
<area target="_blank" alt="" title="" href="https://ecoversities.org/" coords="3510,598,3792,656" shape="rect">
<area target="_blank" alt="" title="" href="https://www.unesco.org/en/futures-education" coords="3656,539,4118,588" shape="rect">
<area target="_blank" alt="" title="" href="https://ronininstitute.org/" coords="3957,773,4161,884" shape="rect">
<area target="_blank" alt="" title="" href="https://www.agilelearningcenters.org/" coords="3486,962,3782,1064" shape="rect">
<area target="_blank" alt="" title="" href="https://www.lenerachelandersen.com/" coords="3272,549,3486,583" shape="rect">
<area target="_blank" alt="" title="" href="https://www.newlocal.org.uk/" coords="3850,1147,4093,1205" shape="rect">
<area target="_blank" alt="" title="" href="https://www.thealternative.org.uk/" coords="3622,1394,4055,1448" shape="rect">
<area target="_blank" alt="" title="" href="https://www.enspiral.com/" coords="4084,947,4273,996" shape="rect">
<area target="_blank" alt="" title="" href="https://metagov.org/" coords="4628,938,4822,981" shape="rect">
<area target="_blank" alt="" title="" href="https://platform.coop/" coords="4288,1190,4574,1341" shape="rect">
<area target="_blank" alt="" title="" href="https://nathanschneider.info/" coords="4706,1414,4953,1458" shape="rect">
<area target="_blank" alt="" title="" href="https://transitionnetwork.org/" coords="3996,1496,4453,1555" shape="rect">
<area target="_blank" alt="" title="" href="https://tellus.org/" coords="3700,1832,4064,1880" shape="rect">
<area target="_blank" alt="" title="" href="https://www.doomeroptimism.com/home" coords="3661,1987,4059,2041" shape="rect">
<area target="_blank" alt="" title="" href="https://www.robhopkins.net/" coords="4171,1613,4356,1642" shape="rect">
<area target="_blank" alt="" title="" href="https://twitter.com/cognitivepolicy" coords="4074,1936,4234,1980" shape="rect">
<area target="_blank" alt="" title="" href="https://www.resilience.org/" coords="3661,2182,3982,2230" shape="rect">
<area target="_blank" alt="" title="" href="https://dark-mountain.net/" coords="3627,2461,4021,2568" shape="rect">
<area target="_blank" alt="" title="" href="https://weall.org/" coords="4404,1999,4647,2155" shape="rect">
<area target="_blank" alt="" title="" href="https://p2pfoundation.net/" coords="4740,1701,5187,1759" shape="rect">
<area target="_blank" alt="" title="" href="https://giveth.io/" coords="5328,1079,5488,1132" shape="rect">
<area target="_blank" alt="" title="" href="https://oasa.earth/" coords="5255,1190,5386,1239" shape="rect">
<area target="_blank" alt="" title="" href="https://app.regen.network/" coords="5104,1419,5449,1462" shape="rect">
<area target="_blank" alt="" title="" href="https://metacrisis.xyz/" coords="5138,1496,5464,1535" shape="rect">
<area target="_blank" alt="" title="" href="https://www.meaningalignment.org/" coords="4987,559,5187,685" shape="rect">
<area target="_blank" alt="" title="" href="https://www.humanetech.com/" coords="5109,714,5488,807" shape="rect">
<area target="_blank" alt="" title="" href="https://nxhx.org/" coords="5201,496,5381,534" shape="rect">
<area target="_blank" alt="" title="" href="https://www.tristanharris.com/" coords="5143,816,5328,850" shape="rect">
<area target="_blank" alt="" title="" href="https://80000hours.org/" coords="5133,49,5400,97" shape="rect">
<area target="_blank" alt="" title="" href="https://www.givewell.org/" coords="5051,296,5259,345" shape="rect">
<area target="_blank" alt="" title="" href="https://www.lesswrong.com/" coords="4434,160,4676,214" shape="rect">
<area target="_blank" alt="" title="" href="https://www.rationality.org/" coords="4793,296,4929,360" shape="rect">
<area target="_blank" alt="" title="" href="https://www.astralcodexten.com/" coords="4448,418,4827,471" shape="rect">
  </map>
```

**Comment by catherinet1** [comment]
See Discord thread for conversation with @aashay who volunteered to help generate the coordinates and HTML code for the map: https://discord.com/channels/1230798369337643030/1247867862769602580

**Comment by catherinet1** [comment]
2024-07-02 update: we now have the coordinates and HTML code for all organisation and people points on the map in this spreadsheet: https://docs.google.com/spreadsheets/d/1UCNiz4PITIUw3jI-nqAHlOJF7VEHitB36NSE9o0PhCM/edit?gid=0#gid=0. 

I made a copy of aashay's (volunteer from Discord) spreadsheet so that we have our own editable copy in our GDrive.

Next is to generate the code to create the HTML map and publish on 2R site.

**Comment by aashay** [comment]
Wrong person 🙂

**Comment by catherinet1** [comment]
My latest try is in this commit: https://github.com/life-itself/second-renaissance/commit/725b8eed0b5e911291ed119f0728f72218e4e5aa. Still does not work.

**Comment by catherinet1** [comment]
Hi @rufuspollock, bumping this as we didn't get round to this in our check-in meeting last week. 

Please could you take a look at my latest commit in which I've tried implementing the HTML image map in pages/mapnew.jsx with a few points (not all of the points) as a test -- you might see something that I do not. 

I tried troubleshooting with chatGPT but hit a dead end here.

**Comment by catherinet1** [comment]
This is still blocked and summary in Acceptance is up to date.

**Comment by rufuspollock** [comment]
I believe this is now moving 🎉

**Comment by catherinet1** [comment]
The issue here was that the size of the image file did not match the size of the image displayed on the page (therefore coordinates and links did not work). 

Steps to get a version working are:

- [ ] Put the image second-renaissance-ecosystem-map.webp in folder public\assets\img\ecosystem
- [ ] Put image map file ecosystem_map.html in folder public\map\
- [ ] Put tsx page ecosystem_map.tsx in folder pages\

Can then view the html image map in /map/ecosystem_map.html, e.g. http://localhost:3000/map/ecosystem_map.html
Can view tsx page in /ecosystem_map e.g. http://localhost:3000/ecosystem_map

🚩 N.B. the webp image size is quite large. You may want to use a graphics drawing program to resize it to say 3072 x 1920 which is screen size of Mac Pro. But then need to redo the corordinates.

**Comment by catherinet1** [comment]
Working HTML image map is published here: https://secondrenaissance.net/map/ecosystem_map.html
And linked from: https://secondrenaissance.net/map

Final step is to share/publicise.

**Comment by catherinet1** [comment]
FIXED. 
- Working HTML image map is published here: https://secondrenaissance.net/map/ecosystem_map.html and linked from: https://secondrenaissance.net/map.
- Announced on: WhatsApp general chat, Discord, LinkedIn, Twitter + noted for inclusion in https://github.com/life-itself/community/issues/1145.
