### ISSUE TITLE
Create /paper/ page

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#312]
```[tasklist]
### Tasks
- [x] Stub page
- [x] Add image (make it linkable)
- [x] Add some info
- [x] Add a download button
- [x] BONUS: Count PDF downloads (e.g. using anonymous analytics tracking) **💬2024-06-03  have enhanced measurement turned on so should be tracking these but not sure how to break these out**
```

issues with current setup ...

- Going to google drive for pdf doesn't result in a download and not obvious for some users how to do that ... (better to have an actual pdf url)
- Sending people to a link that goes to another site is a bit "ugly"
- We can't track downloads

**Comment by rufuspollock** [comment]
FIXED.
