### ISSUE TITLE
Technical build of Cohere+ organisation directory

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#318]
## Acceptance

- [x] Organisation directory displayed on https://secondrenaissance.net/ecosystem/cohere looks good 
  - [x] Has search function
  - [x] Filtering by sector and activity works 
  - [x] Has 300+ profiles **300 profiles are displayed**
  - [x] All logos look good 
  - [x] Add a bit of orientation (short framing text) **Updated the sentence under the Directory heading. Will add more text/framing to page in #315**
  - [x] All partner organisations are included
- [x] Organisation profile pages look good **Profile pages display the following frontmatter: title, url, locations, sectors, activities, start, size, (homepage) image. And free text description + other notes. If a frontmatter field is blank, it is not displayed.**
- [x] Checked sample of ~20-30 profile pages **Checked first 12, and checked a bunch of others while doing image fixes.**

## Tasks

- [x] Create sketch/outline of what directory and profile pages should look like e.g. in Excalidraw (won't be very different from PIP directory and profiles 
  - [x] What frontmatter should be displayed? (look at fields in repo profiles and spreadsheet profiles) **Same as PIP and add: start; size. (url, locations, sectors, activities, start, size**
  - [x] What should the tiles display? **Logo and title. (same as PIP minus url. some URLs were running over into the next tile because they were so long)**
- [x] Create layout (code) for profiles **Cohere profile layout is here: https://github.com/life-itself/second-renaissance/blob/main/layouts/cohere.tsx.** 
- [x] Do technical stuff to apply layout to Cohere+ profiles  
- [x] Do technical stuff to display directory which has search function and can be filtered by sector and activity and shows logo images (see components/custom/OrgList component)  **Directory OrgList is displayed here: https://secondrenaissance.net/ecosystem/cohere**
  - [x] Fix so that logo images show up
- [x] Set up automated import of [spreadsheet](https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit#gid=0) into MD files **Script written and run to generate MD files from csv export of the [spreadsheet](https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit?gid=0#gid=0). Files moved into content/ecosystem/cohere/profiles**
- [x] Build directory 
- [x] Check frontend for any fixes needed (and do them) **⏰ 2-4h**
  - [x] Check overall directory page
    - [x] Some URLs are running over into next tile **Removed URL as think unnecessary anyway. N.B. this means this change was also applied to PIP directory**
    - [x] images (some are white or transparent or not showing up at all, or blurry) 
    - [x] check topic and sector filter for fixes **Fixed ~10 that had issues with activity or sector tags (e.g. showed a blank tag or used "and" instead of "&"**
    - [x] edit heading of directory filter on https://secondrenaissance.net/ecosystem/cohere so that it says sector instead of topic ⭐ **Bonus/Nice to have** ✅ **Done**
    - [ ] add headings to frontmatter fields in profile page? ⭐ **Bonus/Nice to have** **:x: Won't do this.**
    - [ ] Reorder so that "exemplary" profiles show up at top (e.g. first 3 rows) ⭐ **Bonus/Nice to have** :x: **Won't do this. Checked first 12 profiles and made any minor formatting fixes.**
  - [x] Scan ~30 profile pages
    - [x] Check ones that DJ did, as need to fix homepage screenshots for these **Fixed 14 screenshots**
    - [x] Review other profiles **Checked first 12**
  - [x] Add CHE (see email + Signal message from Claudine for logo and sector + activity categories - the Netherlands CHE was added instead of German one)
  - [x] Implement UI tweaks **1) add border to tiles in Org List 2) change background colour and text colour on hover 3) add border to search bar 4) show topics and activities lists in grid layout**

### Hire Software Development freelancer

- [x] Publish job post on Upwork
- [x] Select someone 
- [x] Trial **Had 2h meeting 2024-08-09 where we started working on the task**
- [x] Contract **Drafted here: https://docs.google.com/document/d/1LivAW2fN3GxYdoY964-vwIrpJY_0955upWEuYg8KVrA/edit**
  - [x] Add contractor address
  - [x] Make PDF
  - [x] Add signature
  - [x] Send to contractor to read and sign **Signed contract is here: [Dennis Lee - Tech freelancer contract (1).pdf](https://github.com/user-attachments/files/16566467/Dennis.Lee.-.Tech.freelancer.contract.1.pdf)**
  - [x] Save in Drive **Saved in EU Ecosystem Mapping folder: https://drive.google.com/file/d/1xW4RiVMAPCAj-dr91iHpFPHzE3SufZP6/view?usp=drive_link**

## Key materials

- Spreadsheet (organisations tab): https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit?gid=0#gid=0
- Excalidraw for design: https://excalidraw.com/#room=c373f9b9a59128681b98,1gGW7m3dnNmdMQHdhqxj9A **N.B. DRAFT - in progress**

**Comment by catherinet1** [comment]
## Meeting Notes 2024-08-09 Dennis & Catherine - directory build

GitHub repo: https://github.com/life-itself/second-renaissance
Some organisation profiles are in here: https://github.com/life-itself/second-renaissance/tree/main/content/ecosystem/cohere/profiles 
And the rest are in here: https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit?gid=0#gid=0

Sketch: https://excalidraw.com/

Profile template: https://github.com/life-itself/second-renaissance/blob/main/content/templates/profile.md
Examples of profiles:
- https://github.com/life-itself/second-renaissance/blob/main/content/ecosystem/cohere/profiles/A%20School%20Called%20HOME.md
- https://github.com/life-itself/second-renaissance/blob/main/content/ecosystem/cohere/profiles/Culture%20Hack%20Labs.md

### Profiles layout

#### Frontmatter repo vs spreadsheet

Created - doesn't exist (leave blank)
Contributors - curator
title - title
url - url 
locations - locations
start - start
end - end
size - size
image - homepage image url
logo - logo image url
sectors - 3 columns: main sector, sector 2, sector 3 
activities - main activity, activity 2, activity 3
cohere - doesn't exist in spreadsheet but should be ticked Yes for all 
metadata_version - doesn't exist in spreadsheet but should be "1" for all 

#### Body

[description]

Key People
[key people field on spreadsheet]

Theory of change
[theory of change 1st column]

Key learning resources 
[learning resources] 

Connections
[connections]


## Next actions

- Dennis will start working on Monday (and we'll include time spent today)
- Catherine will send a contract to Dennis
- Dennis will spend 1-2d to finish the scripting, getting the automated import of spreadsheet into MD files in repo
- Catherine will specify what fixes/edits to make to current profile layout and send to Dennis
- Mid-next week Dennis will start work on fixing profile and directory page layout.
- Overall we expect that this should take 7-10 days, inc bug fixes.

**Comment by catherinet1** [comment]
Hi @rufuspollock do you know whether we can easily change this heading from Topic to Sector for the Cohere directory? 

![Image](https://github.com/user-attachments/assets/91cffd66-1da2-4650-a266-00c9751cb614)

i thought it was just text in the page that I could easily go in and edit, but looking at pages/ecosystem/cohere.tsx it doesn't seem to be the case. 

Inspecting element on the directory page brings up a bunch of HTML but I don't know where to find this HTML to edit it.

**Comment by rufuspollock** [comment]
Likely on the compenwnt hence you can't find in page. May need to customise component to change. Nit sure what cost / benefit is.

**Comment by catherinet1** [comment]
FIXED. 

- Directory of 300 organisations taking action for paradigmatic social change in Europe is live at https://secondrenaissance.net/ecosystem/cohere. 
- Profile pages display an image and all key Cohere+ frontmatter fields (including some extra ones which were not part of PIP mapping)
- Some tweaks were made to improve layout/design of Org List (for both Cohere+ and PIP): add border around org cards, change background colour and text colour of org cards on hover, add border around search bar, grid layout of topic/sector and activity categories.
