### ISSUE TITLE
Summer Social Media Campaign for Map and 2R.net

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#320]
We have launched 2R.net and our map is getting traction on twitter. We want to promote and share more of our resources and gain more interest.

## Acceptance

- [ ] Outline of campaign completed
- [ ] Sharing in progress

## Task

- [ ] Draft version of campaign
  - [ ] Heavier focus on twitter
  - [ ] identify accounts to tag 
- [ ] Review paper and pull out items to tweet / quote / pull into LinkedIn posts
- [ ] Divide up map into segments to share
- [ ] Respond to tweets 
- [ ] Bookmark tweets
