### ISSUE TITLE
2R Onboarding Calls - Launch 9th July 

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#321]
To welcome and connect with those encountering and entering the Second Renaissance movement and website. We want to have regular (once a month) connection / heartbeat / watercooler / onboarding calls to allow for individuals to show up and share their questions, and ways they can get involved and support the space.

See Curators Folder for documented information.

## Acceptance

- [x] Announcement live
- [x] First onboarding call takes place _scheduled for 9th July 6pm_
- [x] Following onboarding calls scheduled and advertised

## Tasks

- [x] Draft annoucement
- [x] Other dates for future calls to be added to lu.ma and set up
- [x] Add to Life Itself event calendar
- [x] Set up reoccuring zoom (or Google meet) meeting 
- [ ] Add a page to the 2R.net website with details about these calls and the schedule _currently using a lu.ma calendar - to embed this into the website or create a seperate page_
- [x] Add info for 9 July to lu.ma 
- [x] Post announcement
- [x] Promote on social media
- [x] Inform curators and advisors to share with their own networks

### Onboarding calls outline
- [ ] Feeling into it
- [ ] Meditation, check-in (group or breakout room)
- [ ] Why showed up and feel in to what’s in the space
- [ ] Social / party theme but do we want any type of presentation? (No)
- [ ] Follow the threads of the meeting

**Comment by laurenwigmore** [comment]
FIXED. First call held. Subsquent ones scheduled.
