### ISSUE TITLE
Curators Plan - Next Steps June 2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#325]
Following on from talks and brainstorming, these next action steps have been identified. 

### Summary of current focus 2024-06-25

**Onboarding Journey**

1. A person arrives at our discord channel (from website or substack or discord)  
2. They are invited to introduce themselves (short message no essays)  
3. They are invited to share their wish for the space in a new \#wish channel  
   1. This allows us to gain an understanding of what people (arriving) in the space want in a fun lighthearted way  
   2. This allows people to express a little more about themselves and read others wishes to start to form connection  
4. They are invited to join a connection call (outline of call structure below)

**Next steps**

1. Have a list of simple, specific tasks people can contribute to  
2. See what we’re up to \- have a diagram of what we are up to to allow people to learn more, and have a sense of direction, and orientation 

## Acceptance

- [x] Discord Welcome funnel is live
- [x] Diagram is completed and has been shared
- [x] Task list is available for people to select and contribute to

## Tasks

- [ ] Set up Discord Welcome funnel for onboarding journey
  - [ ] Create a new thread in the Welcome channel called #wish
  - [ ] Draft description of what to write in #wish thread and pin message to top
- [ ] Set up a thread / message for connection call dates and links (?)
- [ ] Create a diagram of what we are up to
- [ ] Identify simple tasks people can contribute to

**Comment by rufuspollock** [comment]
FIXED. Did presentation with "petal-shaped garden" idea end of Aug 2024 and posted into discord.
