### ISSUE TITLE
Get issue tracker and project board up to date post 2R launch

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#327]
```[tasklist]
### Tasks
- [x] Get rid of ready status **✅2024-06-28**
- [x] Close #249
- [x] Add phases **✅2024-07-02**
- [x] Starting situation **✅2024-06-29 48 open issues. board as per screenshot below.**
- [x] Create dedicated view **✅2024-07-03 https://github.com/orgs/life-itself/projects/6/views/7**
- [x] Review all issues **🚧2024-07-01 started with 48 open items** **✅2024-07-08 all assigned to phase. Now 42 open items**
- [x] Remove new status **✅2024-07-08**
- [x] Add Ship and Shape backlogs **✅2024-07-08 ship: https://github.com/orgs/life-itself/projects/6/views/1 and shape https://github.com/orgs/life-itself/projects/6/views/8**
```

## After

![image](https://github.com/life-itself/second-renaissance/assets/180658/b4349e5d-8cd4-49dc-b24e-9b2cbc162582)

![image](https://github.com/life-itself/second-renaissance/assets/180658/9e569871-da15-48d0-b414-45af4a7e915b)

## Before

![image](https://github.com/life-itself/second-renaissance/assets/180658/e9405318-196b-4cb1-b4cb-4bb5e386bd24)

**Comment by rufuspollock** [comment]
FIXED.
