### ISSUE TITLE
🔥 Sort out `/glossary` whose list of terms link to old wiki that is now moved to actual wiki

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#329]
```[tasklist]
### Tasks
- [x] Analyse what we want to do with glossary e.g. do we keep it or move to wiki? **✅2025-01-03 agreed (see comment below) that we migrate to wiki for now.**
- [x] Transfer everything to wiki **✅2025-01-03 Jonah has done most**
- [x] Jonah wrote "Note that I did not transfer links that were only to dictionary definitions or wikipedia articles- only links to authored articles.)" **I'd transfer that stuff too even if it just stubs with that link for now. It is still useful.**
- [x] Remove the pages and glossary on the current
- [x] Add redirects to wiki (or just redirect everything to concept list for now)
```

**Comment by rufuspollock** [comment]
@JonahWilberg agreed let's close. The subtlety here was having a high quality curated glossary somewhere vs the free for all that was the wiki 😄. I think at some point having a good curated list will be useful ... and that can wait.

Last actions:

- [ ]   You wrote: "Note that I did not transfer links that were only to dictionary definitions or wikipedia articles- only links to authored articles.)" **I'd transfer that stuff too even if it just stubs with that link for now. It is still useful.**
- [ ] Remove the pages on the site
- [ ] Add redirects

These actions should be transferred into the body of this issue. **DONE**

**Comment by JonahWilberg** [comment]
I have now transfered wikipedia and dictionary links - in many cases I have also created a basic or stub article. Following Wiki pages created:

- Coherence
- Collective Wisdom
- Community
- Emergence
- Governance
- Lateral
- Meta
- Modernity
- Paradigm Shift
- Postmodernism
- Regenerative
- Social Change
- Systems
- Teal
- Wellbeing economy
- Wisdom

I have also raised a pull request to delete glossary.md and change the link on the ecosystem page to refer to the Wiki.

I also want to review pages in content/wiki and content/stubs to see if there is anything else we should transfer. Should these pages be deleted after I do this?

**Comment by rufuspollock** [comment]
> I also want to review pages in content/wiki and content/stubs to see if there is anything else we should transfer. Should these pages be deleted after I do this?

Yes and add redirects if we can.
