### ISSUE TITLE
Paper 2 on "How" of the second renaissance - how we get there

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#331]
First paper was "what". Second paper is "how"

```[tasklist]
### Tasks
- [x] Draft **✅2024-06-20 have a draft in gdoc (ask if you want to review)**
- [x] Feedback round **🚧2024-07-04 people are giving feedback**
- [x] Revisions **✅2024-08-01 largely done. One small one to do. And could do some bigger ones e.g. more stories**
- [x] Publish **💬2024-08-01 published a current draft. Still some revisions to do ...**
```

**Comment by catherinet1** [comment]
hi @rufuspollock I am interested to review the draft -- can you share it?

**Comment by rufuspollock** [comment]
FIXED. This is up on https://secondrenaissance.net/paper
