### ISSUE TITLE
Second Renaissance Video Introduction for website

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#335]
## Acceptance

- [ ] Video live on website

## Tasks

- [x] Check time estimate from Bijesh to complete the task - **4 hours** 
- [x] Take decision on Lauren in Canva or **Bijesh** 
  - [ ] Find out the dimensions to input into canva ❌ 
- [ ] Get the high quality copy of the images from Sylvie 
  - [ ] Check there is no copyright issue (assuming not as already used)
- [x] Pull script into a document 🚧 
- [x] Record the script in a quiet place, with mic well positioned (no not breathy) so the audio does not need editing or cleaning 🚧 _Lauren recorded to check audio_
- [x] Add which image for which section of the script 🚧  _in progress of sourcing images and videos_
- [ ] Source background music - copyright free 🚧 
- [ ] Create the video
- [ ] Host and release it on YouTube
- [ ] Embed it on the website
- [ ] Share in Whatapp channel, discord, socials
- [ ] Add to Second Renaissance Substack and pin
- [ ] Include release announcement in LI July/Aug newsletter
- [ ] List of 15 people to personally share with and invite to share in networks: 
  - [ ]  Gathering individuals (Paul, Martin, Konrad, Monica, Boaz, Luc, Matt, Maria, John, Marc, Rainer, Petronella, Nina, Hannes)
  - [ ] Praxis Hub (Valerie and Liam)
  - [ ] Curators team
  - [ ] All 2R Advisors (Phil, Naryan, Peter, Jason, Isabela)

### Apetite

- Appetite 2-3 days (24 hours):
**2024-08-12** total time spent so far: 12 hours - Lauren
  - Allocated 8 for Bijesh creation and any re-edits _4 completed so far_
  - 2 hours left for image sourcing and defining before handing over to Bijesh / surplus
  - 2 hours for sharing and promotion once done

[Folder](https://drive.google.com/drive/folders/1EFbr4jKN199gf3fUB5UdCYCeuF13aiSB?usp=drive_link)

Notes: 
Pixabay.com for copyright free music
https://www.youtube.com/@Infraction - copyright free music

**Comment by laurenwigmore** [comment]
Will resume when I return on w/c 22nd July.

**Comment by laurenwigmore** [comment]
In progress. I have been sourcing images, videos and have recorded the script. I will now pull it together into a clearly outlined document / organise and review photos into folders before passing on to Bijesh to create the video.

**Comment by laurenwigmore** [comment]
NOT FIXED. 
Total allocated appetite reached, without any output. 

Summary of conversations and where this is being closed at for now:

- Free stock videos and images were not up to scratch. 
- Paid videos, such as envato, to be used if project opened up again.
- [Copies of videos and images all on the shared drive in this folder](https://drive.google.com/drive/folders/1EFbr4jKN199gf3fUB5UdCYCeuF13aiSB?usp=drive_link)
- Feedback from newer individuals to the 2R space provided useful insight ([see doc](https://docs.google.com/document/d/1MR3TTzGtJtEMM2uHJvlfPWeijI_Sxd0A_D7-PB-RKzg/edit?usp=drive_link)) - - in short 
  - a shorter 30/40 second intro video with an engaging opening question to grab people was felt to be best as an intro
  - the landing page text could then be a longer video, and/or divided up to be played in each of the sections on the website, as a deeper dive
