### ISSUE TITLE
Contact / chat powered by a chat bot

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#34]
Have a contact widget (and maybe page) powered by e.g. crisp.chat

## Acceptance

* [x] Chat widget on site

## Tasks

* [x] Review options **DONE. Chose chatwoot as open source with 11k stars and has a SaaS plan for free**
* [x] Implement (find snippet and embed) **DONE**
