### ISSUE TITLE
Second Renaissance Virtual Workspace Call - 13 Aug 2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#355]
First workspace call - the action oriented sibling of the connection call.
Initially being set up and led by James Baker.
See Curators Folder for documented information.

Event link: https://lu.ma/k5s7zxb9

## Acceptance

- [x] Announcement live
- [x] First call takes place _scheduled for 13th Aug 6pm CET_
- [x] Following calls scheduled and advertised

## Tasks

- [x] Draft annoucement
- [x] Add to Life Itself event calendar
- [x] Set up reoccuring zoom (or Google meet) meeting _done via James' account for this call as he set up the event_
- [x] Add info for call to lu.ma 
- [x] Post announcement on substack and email
- [ ] Promote on social media
- [ ] Inform curators and advisors to share with their own networks

### Copy - Social Media

Let's roll up our sleeves and do the thing(s)! 
Our first Second Renaissance Virtual Workspace Call, an open and collaborative space to tackle projects together is taking place next week! 
This is a "working with the garage door open" space, the doing-oriented sibling to the Connection Calls where we support each other in responding to the needs and opportunities of our times as part of the Second Renaissance movement.

☀ What: Second Renaissance Workspace Call
📆 When: Tuesday August 13th, 6pm CEST / Noon Eastern
📍 Where: Online
🤗 Who: Anyone with projects or the energy to help others
🔗 Register: https://lu.ma/k5s7zxb9

How it Works:
- Quick check-ins to share plans and desires (15m)
- Collaboration offers and breakout organizing
- Work period (60m)
- Sharing and celebration 🎉

Bring a project of your own, or contribute to a default group project. Work on aspects of Second Renaissance movement-building or anything aligned with 2R ideals. You can work independently in the silent co-working space or invite collaborators to a breakout room.

This is our first meeting of this kind, so we’ll figure some things out as we go! You don't need to have attended a prior Connection Call to join. Let's make something amazing together! 🚀

**Comment by laurenwigmore** [comment]
FIXED. Hosted - 16 attended. Next workplace call set up for 27 Aug.
