### ISSUE TITLE
Deep Resilience for a Dark Renaissance - Community Practice Group

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#356]
We want to start a peer learning and support space where we come together to practise psychological, emotional, and spiritual resilience for a dark renaissance.

[Link to working doc](https://docs.google.com/document/d/1BGyfQ9zPFVJDwrHe3KNYt2rfXwkGp84WYpCOAywx3Cg/edit)

The first one is scheduled for 22nd Aug 6-730pm CET

## Acceptance

- [ ] First call hosted with 10-20 people in attendance

## Tasks

- [x] Brainstorm practices
- [x] Define purpose
- [x] Devise Structure of session
- [x] Draft text for announcement ready to go live Thursday 15th
- [x] Set up on lu.ma
- [x] Add to LI events google calendar
- [x] Announced via substack via email
- [x] Copy for promo for social media drafted
- [x] Promotion started Thursday 15th Aug
  - [x] Whatsapp
  - [x] Discord
  - [x] Twitter
  - [ ] IG
  - [ ] LinkedIn
- [x] Have practice session of first practice - Mon 19
- [x] Host session

**Comment by laurenwigmore** [comment]
@catherinet1 if you're OK to make a start on drafting the announcement tomorrow (Wed 14th) I can pick it up on Thursday and continue.

**Comment by laurenwigmore** [comment]
Quick update: 2 meetings had. Output: test of 1st session completed, structure devised, framing (in progress).

**Comment by laurenwigmore** [comment]
FIXED. The Deep Resilience Call went really well.
We had 8 participants join us from the community (all have been involved with 2R/LI or attended a previous event) 🌻 
We have had a debrief and noted down some learnings to implement for the next call taking place on 19 Sept 2024
