### ISSUE TITLE
Art of Second Renaissance website launched

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#361]
## Acceptance

```[tasklist]
### Tasks
- [x] Magazine
- [x] Manifesto and essay
- [x] Website
- [ ] Launch event
- [ ] Launch announcement
```

## Tasks

```[tasklist]
### Website
- [x] Have v0.1 of webpage up at https://secondrenaissance.net/art **✅2024-09-07**
- [x] Design pages properly in figma **✅2024-09-16 https://www.figma.com/design/mOlHG2tAAI9xzumzaXEgM7/Art-of-Second-Renaissance?node-id=124-3**
- [x] Have impermanence page up **✅ 2024-09-14 have a stub at https://secondrenaissance.net/art/impermanence**
- [x] Briefing for helper for website **✅2024-09-16 https://docs.google.com/document/d/1eG3cY4T61qM9O3z89t-fjyc1PeyYS1RZzt_YPT7XqBI/edit**
- [x] Find helper for website **✅2024-09-14 found someone who could help on upwork**
- [x] Brief them helper and review first pass work **🚧2024-09-16 happening today**
- [x] Update /art page and /art/impermanence to full versions from figma
- [ ] **EXTRAS BELOW**
- [x] Have a way to get in touch - can just have email art@lifeitself.org for now. Probably at bottom.
- [ ] Add a way to subscribe for updates (substack newsletter - is there a way to get an embed form that just subscribes to a section??)
```

```[tasklist]
### Misc
- [x] Set up art@lifeitself.org for contact stuff and add Sylvie and Lauren (and Rufus temporarily)
- [x] Set up subsection for art on Substack **✅2024-09-14 https://secondrenaissance.substack.com/s/art**
```

```[tasklist]
### Launch event
```

```[tasklist]
### Tasks
```

**Comment by rufuspollock** [comment]
FIXED. This was done back in Sep 2024.
