### ISSUE TITLE
2R Barn Raising - Write Your Own Postcard - 3rd Dec 2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#368]
## Acceptance

- [x] Barn raising hosted
- [x] 15 people attend 🔥  28
- [ ] Orientation postcards live and availble to the community
- [x] Had fun

## Tasks

- [x] Description and purpose of event clarified
- [x] Image created
- [x] Date, time, and where hosting it agreed _3rd Dec 530pm-930pm CET online - zoom_
- [x] Event set up on lu.ma
  - [x] Set up new Zoom meeting via lu.ma - adjust settings to include waiting room 
- [x] Announcement post drafted 🚧 _shared with team for review. [Link to copy](https://docs.google.com/document/d/10tB1Res8HBF0svkUYaghcNtd5KaDA5_YwbrhmQ5dhuo/edit?tab=t.0)_ 
- [x] Announcement released as a mailout and blog post
- [x] Announcement included in November newsletter
- [x] Social media and whatsapp copy written
  - [x] Intial annoucement shared on usual channels - IG, X, whatsapp, LinkedIn, FB 🚧 
  - [x] Follow up promo completed
  - [ ] Promoted in groups on FB (where/if appropriate) 
- [x] Preparation video script written
- [x] Video recorded
- [x] Video hosted / embedded 
- [x] Video link emailed to all who register(ed)
- [x] Event logistics / set up organised 🚧 
  - [x] Who is host / co-host and expectations defined
  - [x] Breakout rooms
  - [x] Rules / guidance in the space  
- [x] Spreadsheets and resources needed
  - [x] Identified
  - [x] Compiled  
- [x] Draft 1 or 2 Postcard Examples
- [ ] Do we want to set up a dedicated Whatsapp chat just for this event?
- [x] Directly invite people
  - [x] Can do this via the event and others e.g. Jason Sears, advisors, collaborators etc

[Folder link for reference](https://drive.google.com/drive/folders/1hSezdTp8g0z418E20Dg5d22o5VtOu64k?usp=drive_link)

**Comment by laurenwigmore** [comment]
Successful barn-raising event - 41 people registered, 28 attended; some were invited from members during the event. Curators meeting debrief and next action to complete with the postcards to take place on 2024-12-12. 
A wiki introduction event on 2024-12-10 created off of the back of the barn-raising.
