### ISSUE TITLE
2RCon - May 2025

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/second-renaissance#369]
This event aims to unite thought leaders and practitioners to spark cross-disciplinary dialogue and collaboration to support the paradigm shift towards a wiser world. In conversations with pioneers at Harvard University and Life Itself, the intention is to run a 2-day event (1-day unconference and 1-day conference) to bring together individuals who are often fragmented in their work and contributions together. 

**Overview:**
Reimagining the Metacrisis: Towards a Second Renaissance
CTA: An awakening paradigm shift is underway, what part will you play?
Snapshot: Join us to examine the intersections of inner change, social transformation, and academic rigor towards creating a wiser world.

## Acceptance

- [ ] Conference has 300 sign-ups/attendees
- [ ] Conference runs for the 2 days
- [ ] Debriefing and feedback completed
- [ ] Next Steps in place

## Tasks

- [ ] Organising team sourced
- [ ] [Proposal drafted](https://docs.google.com/document/d/1hCKYKSDKj-u3G50ptE3hAgzg_BsReh2xIPF91zJiQWc/edit?usp=drive_link)
- [ ] Sign-off from Rebecca 
- [ ] Date agreed (Friday/Saturday in May) 🚧 
- [ ] Enquiry submitted regarding room bookings 
- [ ] Rooms booked
- [ ] Catering organised
- [ ] AV organised
- [ ] Organisers schedule for the days created
- [ ] Keynote speakers invited
- [ ] Keynote speakers confirmed
- [ ] Speakers submission process set-up
- [ ] Speakers confirmed
- [ ] Schedule finalised and live
- [ ] Website set up
- [ ] Call outs and initial mailout done
- [ ] Marketing promo plan set up
- [ ] Main organisers spreadsheet populated
