### ISSUE TITLE
Geographic Map of Organizations

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#38]
## Tasks

* [ ] Geocode locations **Probably use https://api.opencagedata.com/geocode/v1/json?q=PLACENAME&key=YOUR-API-KEY**
* [ ] Display locations on a map
  * [ ] Identify library **React simple maps seems decent https://www.react-simple-maps.io/examples/custom-markers/**
  * [ ] Implement it
