### ISSUE TITLE
[epic] Visualizations and ways of exploring the data

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#4]
When presenting lots of data we want to display it in a visual way so as to have an efficient way to grasp and explore it

We want to get an overall sense of the shape of the ecosystem and how it connects to other areas of activity

**23 Dec 2021: this is one of those issues that was more research and so could never end (it had no acceptance). At this point i think we've got a good shortlist of initial approaches. In summary:**

* Ternary based on approach style #42 
* Circular packing or hierarchical tree based on topic or activity #47 
  * Richer ecosystem feel if we use double links to topics (and remove central node)
* PCA on the full matrix

**NB: we don't have true "network" data at this point in that we don't have links between nodes. So maps should incline more to PCA style i think (i.e. plotting in 2 dimensions a high dimensional space**

## Acceptance 

* [x] Several visual examples of how we can approach this **DONE. See below**
* [x] Suggestions on which ones to start with **DONE. See discussion above.**

## Tasks

* [x] Research visualization inspiration for the map of the space **See Inspirations section below**
  * [x] Review https://towardsdatascience.com/the-25-best-data-visualizations-of-2018-93643f0aad04 **To arty IMO. Visual candy. Would fail the tufte test**
  * [ ] Review https://informationisbeautiful.net/2019/winners-of-the-world-data-visualization-prize/
* [x] Research analysis options given our type of data
(Possible) next steps

Ideas:

* [ ] ~~Hack out a quick and dirty PCA~~ **WONTFIX for now**
  * [ ] Find node PCA lib (or do in python) e.g. https://github.com/mljs/pca
* [x] Network mapping against topics (not sure how well this will work but guess we have to try) #47 

## Analysis

* We could do topic extraction from the source content e.g. https://towardsdatascience.com/topic-modeling-with-bert-779f7db187e6. Cruder would just be looking for unusual keywords e.g. sensemaking
* Directed network graph linking entities if they share the same topic using force directed
* OR linking entities to topics
* PCA with activity or topics as dimensions
* Visualizing topics using the connections of co-occurence for organizations ...
  * Make topics the size of the number of items in that items
  * https://observablehq.com/@analyzer2004/plot-gallery

Simple

* Circular packing with org logos (if circular)
  * favicon if they have one ...
* Word cloud from org names ...

### Ternary Plot

* Library: https://github.com/davenquinn/d3-ternary
* App: https://www.ternaryplot.com
* Example: https://observablehq.com/@dixonj13/zoomable-ternary-plot

![untitled](https://user-images.githubusercontent.com/180658/144427350-b8627274-e512-4cff-a119-29e3c7124e26.png)

### Network map

Especially useful for e.g. intellectual influences if in a tradition cf #46

https://bl.ocks.org/d3noob/8375092

![image](https://user-images.githubusercontent.com/180658/144620695-45c60c93-9963-42e7-9e36-a2a4de83c9b2.png)

### Force directed

https://bl.ocks.org/heybignick/3faf257bbbbc7743bb72310d03b86ee8

![](https://i.imgur.com/yPfB9Ea.png)

https://observablehq.com/@sandravizmad/force-directed-layout - **this is pretty nice**

![](https://i.imgur.com/pnVSqft.png)

### Circular packing

* https://observablehq.com/@analyzer2004/plot-gallery

![](https://i.imgur.com/DxPUGbm.png)

### Word Cloud

TODO

### Matrix Co-occurence

https://bost.ocks.org/mike/miserables/

![image](https://user-images.githubusercontent.com/180658/144748940-fcad922d-12d1-4793-bd03-4d98671a001f.png)

### Map of the Internet 2021

Pseudo-map like e.g. https://www.halcyonmaps.com/#/map-of-the-internet-2021/  and more like this on www.halcyonmaps.com/

![image](https://user-images.githubusercontent.com/180658/129439632-46993899-6492-4b9a-b1af-e79e8a05d40e.png)

### Rappers word usage

https://pudding.cool/projects/vocabulary/index.html

![image](https://user-images.githubusercontent.com/180658/129439581-48a3b36c-d947-49dc-96ed-c5ff331e0c4b.png)

### The Political Compass

![image](https://user-images.githubusercontent.com/72795023/130228019-a0d90b0c-5ff4-4076-b571-5845c916d575.png)
