### ISSUE TITLE
[vis] Ternary Plot of orgs against approach

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#42]
Create a ternary plot based on the three (sum to one) "approach to change" dimensions

* Library: https://github.com/davenquinn/d3-ternary
* App: https://www.ternaryplot.com
* Example: https://observablehq.com/@dixonj13/zoomable-ternary-plot

![untitled](https://user-images.githubusercontent.com/180658/144427350-b8627274-e512-4cff-a119-29e3c7124e26.png)

## Acceptance

* [x] Ternary diagram based on approach type
* [x] Can see info on org on hover

## Tasks

* [x] Identify library **DONE. Use d3 and d3-ternary https://github.com/davenquinn/d3-ternary**
* [x] Try it out with some simple data
* [x] Design it (a bit) **In progress https://docs.google.com/drawings/d/14MEAE9PC1Vp9rb6QlDejat62PRXS75iprkGOl2ziD7I/edit**
* [ ] Explanatory text @rufuspollock or @theo-cox 
* [x] Hover shows label **DONE: with simple title** (though not obvious)
* [x] Better hoverable/tool-tip labels **DONE** <img src="https://user-images.githubusercontent.com/180658/147554424-49d989f3-d964-4f9f-88ec-0035c974f8fd.png" height="150" />
  * [x] Make text a bit smaller 
  * [x] Remove border (?) 
  * [x] Use a nicer font (either inconsolata/source code mono or our standard font for site which is nunito sans)
* [x] Try out showing all labels (and paste a screenshot in comments) **DONE. See comment below. Basic conclusion is a bit messy but useful. Maybe if we make labels a lot smaller and maybe rotate to 45 degrees**
  * [x] Reduce font size to 6 or 7 and retry
  * [ ] ~~Rotate labels 45 degrees~~ **Not worth it**
  * [ ] if good we can add a toggle for this (later)
* [x] Color organization "dots" based on their topic (or activity) so we can see that as well
  * [x] Assign color scale to primary topic **Using d3 color scale**
  * [x] Apply that to organization dot
  * [x] Show scale with explanation - see https://observablehq.com/@d3/color-legend **DONE: currently outside of SVG**
    * [x] Can we show this stacked and several font sizes down e.g. like 
![image](https://user-images.githubusercontent.com/180658/147555164-5474d055-a2b1-443a-9b3d-51ce8d264d46.png)
    * [x] Move legend below chart
* [x] Add our logo - see `public/life-itself-logo.svg` (position top right probably) **DONE. See screenshot in comment below**
   * [x] Move logo in a bit to be above diagram e.g. like  <img src="https://user-images.githubusercontent.com/180658/147555497-b1eeaaeb-454e-4e71-aa3a-05326683d6b9.png" height="100" />
   * [x] Move the life itself logo up a bit - align with top and right if possible (so RHS of logo is flush with right of visible diagram)
* [x] Make circle size 3 and see what we think (take another screenshot)
* [x] Re-add the scale on the sides with percentages (and maybe grid) (?) *not sure as what are the labels, maybe you need an arrow?* ![drawBasicTernaryPlot](https://user-images.githubusercontent.com/180658/147555871-04eba0d1-0be0-42af-a271-e1436ca9b1a2.png)
  * [x] Probably remove or significantly change anchor circles
  * [x] re-add anchor labels (and closer)
  * [x] Make anchor labels smaller e.g. size 10
  * [x] Move anchor labels closer to anchor point
  * [x] move inner change back to top (same orientations as before)
  * [x] move red axes arrows out of diagram and make a bit shorter (and same color as axes)
  * [x] bring back a small black dot at the corners (?)
  * [x] maybe make the color of axes a bit "black" e.g. `#333`
* [x] have labels to the right of the dots (and closer if possible) (rather than below)
  * [x] don't clip outside of the border (but leave the border for now) 

Bonus

* [x] Making the diagram bigger / full screen **DONE**
* [x] (?) Remove big red dots and divide with lines as per sketch below **IN PROGRESS Removed big red dot - separating lines maybe not important for now**
    <img src="https://user-images.githubusercontent.com/180658/147222862-e637808c-9fa4-4ebf-85b1-ec602ceafcc1.png" height="250" />
* [ ] Zoom support - see https://observablehq.com/@julesblm/introducing-d3-ternary#zooming
* [ ] export svg / png
* [ ] PNG and SVG export / embed
* [x] Make colors nicer see e.g. https://github.com/rufuspollock/ux-patterns/issues/5

Someday maybe

* [ ] Labelling improvements e.g. label collision detection and avoidance see e.g. https://github.com/tinker10/D3-Labeler and https://stackoverflow.com/questions/17425268/d3js-automatic-labels-placement-to-avoid-overlaps-force-repulsion
* [ ] Search to highlight an organization i.e. i can search with a name and then select an organization and it highlights in the vis (maybe for more than one org)
* [ ] Show both topics the org is associated with (maybe a bullseye coloring of the dot?)

## Documentation

* Library: ...
* A direct example: https://observablehq.com/@dixonj13/zoomable-ternary-plot
