### ISSUE TITLE
[epic] Push to v1-beta Dec 2021

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#43]
Visualization and categorisation

- [x] Finalize [All of us] 
 -  [x] Approach 
 - [x] Activity  - Fix the one org with arts atm
 - [x] Theme/Topic 
- [x] Apply them to first 20 or so organizations [Julie -> Theo to check]
- [x] Visualize [Rufus]

Content

- [x] Front page update [Theo] (brief check in first with Rufus]
  - [x] TODO Theo to finalise wordsmithing
- [x] Directory - TODO 
  - [x] ❗What about all the items with "blank" in their "include in v1" column? Do we include? If we include do they have content etc. @theo
  - [ ] E.g. commonweal has no content
  - [x] Julie add Prosocial World and Moral Imaginations
- [x] Can we add curator instructions **DONE: very basic info up here https://ecosystem.lifeitself.us/curators**
  - [x] Review Julie instructions @theo
