### ISSUE TITLE
[vis] Network map plot using hierarchical structure e.g. link to topics

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#47]
Something like this - see #4 for background

<img src="https://user-images.githubusercontent.com/180658/144765383-cce71f89-3ba4-4204-a9ee-9e7cd1072e09.png" height="250" />

## Tasks

* [x] Get a working example using the data **DONE. https://ecosystem.lifeitself.us/vis2**
* [ ] Tweak
  * [ ] Introduce 2nd level connections (2nd topic)
  * [ ] plus some "hand-added" connections - cf our 2020 map https://lifeitself.us/wp-content/uploads/2021/09/Social_Change_Ecosystem-2048x1253.png
* [ ] Coloring nodes - color via location in approach spaces
  * [ ] show scale on graph
* [ ] Beautifying e.g. font

Options

* [ ] Be able to drag and drop nodes and have them fixed
* [ ] (?) Freeze the graph and use that permanently (?)
* [ ] Export png / svg and use that by default as main image
* [ ] Show names (at least of intermediate nodes)
* [ ] Add images of orgs to nodes - cf http://bl.ocks.org/eesur/be2abfb3155a38be4de4
  * [ ] Or at least show on hover etc
