### ISSUE TITLE
Optimize Image loading

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#53]
Is this worth it?

When I visit the site I currently load a lot of images (esp on the front page) and this is very slow (and uses lots of bandwidth) and I want to use image optimization so that ...

## Acceptance

* [ ] What is required for image optimization to work
* [ ] Is it worth it
* [ ] Do it if it is ... (details to be added)

## Tasks
