### ISSUE TITLE
Ternary plot on front page

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#56]
When visiting the site I want to have a visual overview so that I get a sense of this ecosystem and who is in it

Select our best visualization and put prominently on the front page. Make it also downloadable / shareable (with our logo on).

Also make a link through to other visualization options (and/or embed other visualizations further down)

## Acceptance

* [x] Ternary visualization on the front page somewhere prominent @khalilcodes 
	* [x] choose where it goes (e.g. just underneath hero, or in the overview section) @theo-cox to discuss with @khalilcodes 
* [x] intro / caption text written "Fig X: caption ..." @theo-cox **See here: https://docs.google.com/document/d/1VIYhUF1Ti8PGqXIuqs-l4G28_1ewxfKuNcdmUwNWPUk/edit?usp=sharing**
	* [x] title
	* [x] bit of an explanation

## Tasks

* [x] Move core code into a component so it can be used in front page and a separate page
* [x] "Embed" into front page
* [x] write intro text ...
