### ISSUE TITLE
Clarifying process by which new orgs are added to the map

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#61]
Just tried to rebuild database and got errors ...

![image](https://user-images.githubusercontent.com/180658/151560878-885f925b-d22c-4322-888b-635110c1aee3.png)

Key questions/things to flag for me:

* We need to set id for every organization or the database build works
* We need to set the column for rd_1_focus as that determines whether orgs are included ...
* Some orgs in there seem to have very little info or info in odd columns

Bigger picture:

* Do we want a "to process" sheet separate from the main sheet perhaps going forward (or use main sheet but use rd_1_focus flag or similar)

![image](https://user-images.githubusercontent.com/180658/151560816-816849a2-580b-4d4c-97af-68bb899f9772.png)

### Tasks

@catherinet1 
- [x]  Review rd_1_focus column **rd_1_focus column is currently filled for all orgs**
- [ ] Fill in missing info/check quality of info for all orgs which are green or yellow on rd_1_focus 
- [ ] fix broken images: New Economics Foundation; Path Retreats; Building Belonging

@khalilcodes 
~~- [ ] automate setting of org id~~ 
- [ ] automate transfer of info from google form responses sheet to database **Not a priority right now**
