### ISSUE TITLE
Ecosystem Blog

### ISSUE THREAD

**Issue by khalilcodes** [life-itself/second-renaissance#67]
Markdown Blog setup for ecosystem similar to https://lifeitself.com/blog

Aside: also could make "banner" at top of page customizable.

## Job Stories

**News/Updates** When i go to a site or project i want to know what's been happening (and gives me a sense if active) so that I know what to explore

TODO: blog job story ... (what is motivation for that)

## Acceptance

  * [ ] Blog page with all posts
  ~~* [ ] Authors page~~ **not necessary right now**
  * [ ] Tags/categories for blogs
  * [ ] SEO Twitter card support	
  * [ ] Components support
  * [ ] Images support - next/image

## Tasks

* [ ] Create image which can be used for Twitter cards when tweeting blog posts @catherinet1
