### ISSUE TITLE
Twitter cards 

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#68]
When I'm tweeting about my ecosystem mapping project and website, I want a visually attractive Twitter card with an image so that people who see the tweet are likely to click on the link and visit the ecosystem website

When I see a link on Twitter, I want to see a preview image and title which gives a sense of what the link is about so that I know whether or not I want to visit the page

**Acceptance**
- [x] When I tweet a link to ecosystem site, a visually attractive Twitter card with an image and clear title + preview text appears

**Tasks**
- [x] Discuss with @khalilcodes  current status and next steps. **Twitter cards are pretty much good to go (*see previews below*), except for orgs which only have an svg image. Secondary issue is broader discussion around what we consider a good enough/better image to represent organisations and how much time we'd be willing to spend on that (images not just for Twitter cards but also other marketing purposes)**
- [x] Ensure that all orgs have a usable image (i.e. not svg format)
