### ISSUE TITLE
Ecosystem Marketing Q1

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#71]
### Action Plan Summary
This is a priority action area for the ecosystem stream Q1. Focus on low-hanging fruit (particularly building up foundational social media activity on Twitter and Instagram and evergreen content such as key idea summary essays on ecosystem site). Also reaching out to platforms that already have attention, starting with platforms we have access to, e.g. Emerge. See [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1985170706). Perhaps begin developing our own podcast/recording conversations with ecosystem actors as this would be a good source of valuable, reusable content.

### Acceptance / Projected outputs
- [x] 7 tweets per week @nathenf **Some tweets and other social media content related to ecosystem mapping were published**
- [x] 1-2 IG/FB posts per week @nathenf 
- [x] 8 articles posted in information library @EilidhRoss1 **6 articles (key tradition summaries) were posted on Life Itself blog**
- [ ] Ecosystem mapping shared with/in 50 contacts/fora documented in Ecosystem Campaign tab on [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1985170706) @catherinet1 **Not done as we switched focus away from this project for Q1**

### Tasks
- [x] [Summary essays of key traditions/movements/philosophies in the metamodern ecosystem](https://github.com/life-itself/community/issues/128#)
- [ ] Fill contacts into Ecosystem Campaign tab of CRM database
- [ ] Draft messages
- [ ] Share
