### ISSUE TITLE
Making ternary plot interactive

### ISSUE THREAD

**Issue by olarubaj** [life-itself/second-renaissance#75]
## User story

A user can explore organizations mapped on the graph and easily learn more about a given organisation by clicking on its point on the plot. A user can also see where the filtered out (in the Profiles section below) organisations lay on the plot. Maybe there are some interesting corelations/patterns?

## Tasks

- [ ] enable clicking on the organisation on the plot to learn more
- [ ] add helper lines on hovering over a given organisation with percentage indicators to aid quicker understanding of the mapping
- [ ] show only filtered results on the graph or at least mark them differently?

## Maybe

* Maybe the ovelapping points on the plot could be solved by making them transparent and only partially overlapping - create clusters of points that stick to each other, e.g.:

![image](https://user-images.githubusercontent.com/104430201/167310307-b70116e4-c734-487e-a8d0-d99260157121.png)
