### ISSUE TITLE
Convert json databases to markdown files with frontmatter

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#79]
Convert current database in json in `data` into markdown files with structured data in frontmatter. Part of #78 

General principle: text content goes to body and structured metadata to frontmatter.

Nice to have some kind of standard ordering in the yaml frontmatter. For now, let's follow spreadsheet ordering if we can (if we can't and just alphabetic that's ok!).

## Acceptance

* [x] Convert profiles (organization.db) to markdown pages i.e. for each entry in organization.db we have an a file in `content/profiles/{id}.md`
  * [x] description is file body
  * [x] all other fields become yaml frontmatter except
    * [x] any email stuff => deleted
    * [x] phone => deleted
    * [x] `activity orig` => deleted
    * [x] image_homepage => delete
    * [x] images_extra => delete
    * [x] transparent_logo => delete
    * [x] notes_data_entry => delete
    * [x] inner, cultural, systems map under a new top level attribute `social_change` and numbers are numbers not strings
    * [x] started / ended are integers and so not quoted
    * [x] `name` renamed to `title`
    * [x] convert `rd_1_focus` to `curation_status`
  * [x] Bonus: remove blank locations
* [x] Convert topics i.e. for each topic one file in `content/topics/{id}.md`
  * [x] name to title 
* [x] Convert activitys i.e. for each topic one file in `content/activitys/{id}.id`

## Tasks

* [x] Convert organization.db to profiles on disk =>
  * [x] Create node script in scripts
  * [x] Create a first simple test using e.g. first entry in db
  * [x] Pass the test
  * [x] Add function to run this on organization.json
  * [x] Add to cli.js
* [x] Convert `data/topic.json` to markdown files in `/content/topics` directory
* [x] Convert `data/activity.json` to markdown files in new `/content/activitys` directory
* [x] Single function to do all of this that we can call from cli.js
* [x] Add this to cli.js
