### ISSUE TITLE
Flowershow conversion

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/second-renaissance#81]
Introduce flowershow and/or refactor towards it.

## Acceptance

* [x] Landing page still working and similar to before (not exact layout or look but in functionality) **✅2022-07-08 see https://ecosystem.lifeitself.us**
* [x] Profile page similar to before **✅2022-07-08 https://ecosystem.lifeitself.us/profiles/life-itself**
* [x] Can still use components specific to ecosystem e.g. around the viz **✅2022-07-08 see front page which is doing this**
* [x] Using contentlayer **✅2022-07-04 - this is working.**

NB: one big issue is we are passing all profile data to every page so the basic page load is now 500kb!! This is because this is the only way we have found to pass data in with contentlayer and mdx atm. See https://github.com/flowershow/flowershow/issues/20 for details.

## Tasks

* [x] Push current ecosystem to backup git repo e.g. ecosystem-old (this is a new repo on github so that we can keep issues with ecosystem)
* [x] Start a clean separate folder and git repo
* [x] Install flowershow into the root folder using degit or npx create-next-app (flowershow/template/default ??) **✅2022-06-29 using degit as very fast and allows clean reinstalling**
* [x] copy over content folder
* [x] Add userConfig.js
* [x] Run app

Refactor

* [x] Front page working **using mdx in `content/index.md`**
  * [x] Copy over index.js (think this is easier than trying to put stuff in markdown - unless we use tailwind in markdown) **❌ does not work**
   * [x] jsx syntax in markdown eg. `<div className="...">....</div>` See `content/index.md`
         - svg needs to be wrapped in a fragment ie. <>...</> so added this to mdx components for default behavior
   * [x] custom components in components/mdx.js: 
         - ```Link, Hero, Search, TernaryPlot, CircularVis```
   * [x] add profiles/orgs for prop values in markdown eg. `<TernaryPlot orgs={orgs} />`
          - `useMDXComponent(body.code, { orgs: ... }` will make orgs accessible as a variable globally (in md files). See `pages/[[...slug]].js` for implementation.
   * [x] contentlayer setup:
          -  defined two separate document types `Profile` and `Topic` with respective fields in `contentlayer.config.js`
          ```javascript
          import { allDocuments, allProfiles, allTopics } from 'contentlayer/generated'
          /** 
          allDocuments => [ allPages, allProfiles, allTopics ]
          using allDocuments to generate all paths
          allProfiles => getOrganizations()
          */
          ```
   * [x] search working - ✅  **Done** *after converting to frontmatter* `name => title`
   * [x] Data fix: After orgs script conversion in`content/profiles/...`, values in frontmatter differ from the orignal json. eg... `topic: 0 // this was an empty array [] in the json db`. Why we need an array? => used in vis components to map by topics **FIX: resolve 0 values to array for lists in `contentlayer.config.js => Profile`**
* [x] Profile page working ✅ **Done**
   - custom layout for profiles in `layout/profile.js`
   - default layout in contentlayer config for Profile is set to: `layout: profile` 

### Where we are now

Current layout of pages

```
├── [...slug].js
├── _app.js
├── find.js
├── index.js
├── profile
│   └── [...slug].js
├── search.js
├── topic
│   └── [...slug].js
└── vis2.js
```

Content folder:

```
├── about.md
├── contribute.md
├── curators.md
├── glossary.md
├── outline.md
└── vis.md
```

* profile/slug.js generates the profiles using a specifc layout
* search.js runs off the org db

### Future

Layout of pages

```
├── [...slug].js # flowershow
├── _app.js      # flowershow
├── find.js      # hmmm ...
├── index.js     # hope this moves to markdown content
└── vis2.js      # probably can delete / or move to markdown
```

Content folder:

```
about.md
contribute.md
curators.md
glossary.md
outline.md
vis.md
profiles/
  life-itself.md
  dark-mountain-labs.md
  ...
blog/ ???

related-efforts # other mapping initiatives
```

### Some interesting findings (only for info)

From https://www.contentlayer.dev/docs/reference/source-files/define-document-type#contenttype-default-markdown

With contentlayer we can even source content from json/yaml files using the contentType...

```javascript
const Org = defineDocumentType(() => ({
  filePathPattern: '**/*.json',
  contentType: 'data'
  // ...
}))
```
Also global configs... [documentation](https://www.contentlayer.dev/docs/reference/source-files/define-document-type#issingleton-default-false)
```javascript
defineDocumentType(() => ({
  name: 'GlobalConfig',
  filePathPattern: `config/global.yaml`,
  isSingleton: true,
  // ...
}))
```
